### ISSUE TITLE
🔴 Ecosystem Project Idea: Global Passport NFT

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#10]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station) is a simple and unified way to make attestations on OP Mainnet, OP Goerli, or any other OP Stack-based chain.

You can use attestations as a way to show that you have visited certain cities or countries. Users could keep track of their own trips by adding "stamps" to their passport NFT whenever they're in a new city or country.

## Possible Features

- Allow users to create attestations that they've visited certain locations.
- Allow users to see a UI that shows them all of the places they've visited.
- Allow users to see what places other people have visited.

**Comment by mgarciap** [comment]
> The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station) is a simple and unified way to make attestations on OP Mainnet, OP Goerli, or any other OP Stack-based chain.

Broken Link (404). Shouldn't be https://community.optimism.io/docs/identity/atst-v1 ?

Same problem with all issues tagged as [Attestations](https://github.com/orgs/ethereum-optimism/projects/31/views/4?filterQuery=label%3A%22Tag%3A+Attestations%22)

**Comment by immaxkent** [comment]
"their NFT passport" refers exactly to which passport, if any? Does this idea require the development of a passport itself?

**Comment by robbiesumner** [comment]
There is no "NFT Passport", the idea is to create one

**Comment by imajus** [comment]
We've implemented an MVP of the proposed idea during the recent Superhack hackathon. 
For this project, we've decided to give anyone opportunity to grant stamps to anyone else for now, just because it makes it easier to implement. We rely solely on honestly of the community, so this is not necessarily a sustainable business model. 

To make the implementation more reliable and trustworthy we thought of the following ways:
- Fully integrate with Worldcoin and let only users verified via WorldID to be granting stamps to other
- Introduce another attestation which allows users to grant stamps. Not sure yet about the system for granting/withdrawing of such attestations. 
- Establish contact with local guides, business and entrepreneurs all over the world, whom we could trust the ability to be granting the stamps to the users
- ... and some other ideas, as the possibilities are almost unlimited

You may find the source code of the MVP here: https://github.com/HarshalBhangale/PassportGlobal
And here's a short demo: https://www.youtube.com/watch?v=7PRcn4tSKC8

**Comment by jacobleegithub** [comment]
![IDGO-logo_white](https://github.com/ethereum-optimism/ecosystem-contributions/assets/14127551/d8d15ea4-37b0-4f99-a91b-dd37734289a5)

### Introduction
A digital portal for every township 

IDGO is a web3 content publishing app designed to enhance tourism experiences through a blend of professional and user-generated content. It offers a diverse range of activities including guided tours, outdoor adventures, cultural experiences, dining, and entertainment. With its social media elements, IDGO allows travelers to connect, share itineraries, and engage with others. The introduction of the NFT Passport concept further innovates the platform. Local communities or businesses can issue these passports, enabling tourists to collect unique digital stamps and attestations for their experiences. This feature creates a more immersive and interactive travel experience, encouraging exploration and engagement with local city or township portals. Whether for vacation planning or travel inspiration, IDGO with NFT Passport integration offers a novel approach for travelers eager to explore and connect.
Market Problems

### No more blogs ads disaster 

Inaccurate or outdated information: Tourists often rely on search engines and online travel guides to plan their trips, but the information provided may not always be up-to-date or accurate, leading to confusion or disappointment.

Overwhelming amount of information: The sheer volume of information available online about destinations and activities can be overwhelming for tourists, making it difficult for them to filter out what is most relevant to their interests and preferences.

Lack of personalization: Traditional tour companies and travel agencies may not always provide personalized recommendations or suggestions based on an individual's preferences or interests, leading to a generic and unfulfilling travel experience.

Limited opportunities for interaction: Tourists may not have the chance to engage or interact with the local culture in a meaningful way, as traditional tour companies and travel agencies may not offer opportunities for authentic cultural immersion.

### Solutions
Play like local and play like pro

### IDGO Story Book

By providing a wide range of experiences in the "Story Book" created by power users, we can cater to a diverse audience of tourists with different interests and preferences. This can help to make the platform more engaging and increase user retention.

### NFT Passport

The NFT Passport is designed to create unique digital portals for local communities. For instance, a community in Okinawa can issue its own NFT Passport. This passport allows them to curate and showcase selected tourism articles, experiences, and attractions specific to Okinawa. Essentially, it acts as a specialized tourist portal for the area, offering visitors a personalized and immersive experience of the local culture, history, and attractions.

### IDGO Rewards

To incentivize user engagement and contribution, IDGO provides a token reward system that rewards users for creating and sharing high-quality content, rating and reviewing activities and destinations, and engaging with other travelers. This could be achieved through a smart contract-powered reward system that distributes tokens based on user actions and contributions.
Technology

### Layer2 Blockchain

By using Optimism, IDGO can leverage its fast transaction times and low fees to provide a more efficient and cost-effective platform for tourism social media. Additionally, Optimism's compatibility with the Ethereum Virtual Machine (EVM) means that IDGO can benefit from Ethereum's existing developer ecosystem and tooling, while also taking advantage of Optimism's Layer 2 scaling solutions.

### Encrypted IPFS storage

IDGO offers both open and paid content on its platform. By using encrypted IPFS storage, IDGO can ensure that user-generated paid content is protected and only accessible by authorized users who have paid for access to the content. This can help to build trust and confidence among users, and create a more secure and privacy-focused platform for tourism social media.

### AttestationStation

The AttestationStation in IDGO will be a pivotal feature for authenticating and commemorating travel experiences. It allows users to make blockchain-based attestations of their visits to various locations. This technology not only verifies their travel but also enriches their digital storybooks with genuine, timestamped proof of their journeys. AttestationStation provides a novel way for travelers to collect and showcase their adventures, making each journey uniquely verifiable and memorable. This integration enhances the social aspect of travel, encouraging exploration and sharing within the local community.

### IDGO Features

Story Books: A collection of fun and tourism story books for tourists, including guided tours, outdoor adventures, cultural experiences, dining and entertainment options, and more.

NFT Passport: Local communities or organizations can issue NFT Passports to create a local portal to promote local tourism and cultural experiences. Users can collect stamps and rewards through the NFT Passport.

Incentivizes positive user behavior: IDGO encourages users to contribute high-quality content to the portals.

![UI_1](https://github.com/ethereum-optimism/ecosystem-contributions/assets/14127551/47d624a9-b99a-4f4e-91f9-a32d8524b103)

![UI_2](https://github.com/ethereum-optimism/ecosystem-contributions/assets/14127551/2808ba76-2ee9-45f0-b1f6-8dac2326bacb)

**Comment by jacobleegithub** [comment]
Is there any possible to get the resources of grant to support this idea of NFT Passport and continue develop above IDGO based on the Global Passport and AttestationStation on Optimism?
