### ISSUE TITLE
🔴 Ecosystem Project Idea: Transaction Replay Tool

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#100]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

As it currently stands, users need to utilize the SDK or other low-level mechanisms to replay L1 => L2 or L2 => L1 transactions that ran out of gas. This can be complex for average users. A good tool would provide an interactive user interface for replaying transactions. This tool aims to simplify this process and make it more accessible.

## Potential Features
- **Query and Display Failed Transactions**: The tool would provide functionality to query both L1 and L2 chains using a user's public address to find transactions that have failed due to running out of gas. Should also be able to support searching by a specific transaction hash.
- **Customize Gas Limit**: The user interface would allow users to specify a higher gas limit for replaying the failed transaction.
- **Safe Replaying**: Before replaying, the tool should provide a cost estimation for the transaction and ask for user confirmation, this makes sure that the custom gas limit is going to be high enough.
- **Tutorial and Help**: The tool would include a brief tutorial or walkthrough on how to use it, along with tooltips or help text to guide users.
- **Real-time Updates**: The tool would offer real-time updates on the status of the transaction once replayed.
- **Transaction History**: It should have the functionality to keep a history of all replayed transactions for a given address.

## Impact
- **Increased Usability**: This tool will drastically improve the experience for users who face gas issues during transactions between L1 and L2.
- **Accessibility**: It will make L2 interactions more accessible for non-technical users by removing the need to use the SDK for these transactions.
- **Reduced Transaction Failures**: The tool will help to reduce the number of failed transactions on the network, leading to improved overall network health.
- **Better User Experience**: By giving users control over their gas limits, it provides a more personalized and user-friendly interaction with L2.
- **Educational**: This tool can serve as an educational resource for users to better understand gas costs and transaction dynamics in L2.

**Comment by buildooor** [comment]
I created an Optimism transaction replay tool UI that lets users input an account address to see recent cross-chain messages for the account and replay transactions the are either unrelayed or a failed relay. It lets the user specify a custom gas limit and shows the estimated gas cost in ETH.

Source repo:
https://github.com/buildooor/optimism-transaction-replay-tool

Live URL:
https://optimism-transaction-replay.vercel.app/

The rest of the suggested features coming soon.
