### ISSUE TITLE
📝 Draft Project Idea: RPGF Project Discovery

### ISSUE THREAD

**Issue by JSeiferth** [ethereum-optimism/ecosystem-contributions#105]
**What is a Draft Project Idea?**

A Draft Project Idea is a concept for a project within the Optimism ecosystem that is generally considered valuable but has not yet been fleshed out into a clearly defined product. Draft Project Ideas may be converted into Ecosystem Project Ideas as they are explored further and more thoroughly specified.

---
### Summary
[Retroactive Public Goods Funding (RetroPGF) Round 3](https://community.optimism.io/docs/governance/retropgf-3/) will take place this fall and will distribute 30M OP to reward contributions that have supported the development and adoption of Optimism. This project idea will **support badgeholders (voters in RetroPGF) in their efforts to discover projects to vote on** and by doing so contribute to a more accurate evaluation of projects and the overall success of RetroPGF 3.

**OP Labs or Optimism Foundation Contact:** Jonas (gh: @JSeiferth, TG/Discord: **@jonassft**)

### Problem outline
The [RetroPGF Voting Application](https://github.com/ethereum-optimism/ecosystem-contributions/issues/104) will provide basic filtering, sorting and search features, but **these might not be sufficient to allow badgeholders to find projects relevant to their expertise within the total pool of hundreds of nominated projects.** 

### Possible Solution
This Ecosystem Project Idea is about building a product that allows badgeholders to more effectively find projects in areas they have high expertise in. We’re excited to see a different solutions and experiments that extend the RetroPGF toolkit and maximize the success of RetroPGF 3. Some ideas of possible solutions: 

- **Personalized Project Proposals**: Utilize a machine learning model (LLM) that suggests projects based on the expertise of badgeholders.
  
- **Project Clustering**: Group projects based on their mentions in Lists, enabling badgeholders to see the most popular or trending projects.
  
- **Automated Tags**: Generate tags automatically derived from project descriptions to make searches more intuitive and effective.

### Impact

- **Enhanced Project Discovery**: Badgeholders can effortlessly discover projects that match their areas of expertise, ensuring they cast informed votes.  
    - Measurement: The product is used by a portion of badgeholders
  
- **Increased Participation**: A more intuitive discovery process will increase the number of badgeholders actively participating in RetroPGF Round 3, increasing the overall accuracy of the round. 
    - Measurement: Qualitative feedback from badgeholders that the product increased the number of projects they voted on

- **Feedback Loop**: By tracking badgeholder interactions and gathering qualitative feedback, this project could inform future iterations of RetroPGF applications. 
     - Measurement: Future iterations of RetroPGF applications build on the learnings of this product

The ultimate aim is to maximize the success of RetroPGF Round 3 by ensuring badgeholders can effectively find projects hey have the most context and knowledge about.

**Comment by Maxservais** [comment]
Hello @JSeiferth, do you think it would make sense to translate this into a Mission Request and have one of the top 100 delegates sponsor it to move it to a vote?

If so, I could probably draft something before the deadline (17th of January)

**Comment by Maxservais** [comment]
![image](https://github.com/ethereum-optimism/ecosystem-contributions/assets/43566493/304997d1-f718-4f5d-9952-5fee67cb03c5)

I think this issue can be closed!

cc: @smartcontracts
