### ISSUE TITLE
🔴 Ecosystem Project Idea: Voting Badge Attestation Visualizer

### ISSUE THREAD

**Issue by JSeiferth** [ethereum-optimism/ecosystem-contributions#107]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

**This project is for creating a frontend that allows users to explore how RetroPGF voting badges are distributed.**

Recently, the voting badge distribution for RetroPGF round 3 has kicked off - you can find the full announcement [here](https://gov.optimism.io/t/retropgf-3-voting-badge-distribution/6557) 👈
To drive transparency and understanding it would be valueble to visualize how voting badges are distributed. Badgeholders are selected through a multiple selection methods. 
@smartcontracts prev built a frontend that allows you to visualize a specific attestation schema. You can find the repo [here](https://github.com/smartcontracts/coolgraph) https://github.com/smartcontracts/coolgraph 👈

![Image](https://github.com/ethereum-optimism/gov-internal/assets/43515441/0c769250-1c69-4b95-a404-b02e26759844)

This project can pick up on the existing visualizer and make minor changes to visualize the voting badge distribution or add new features that make this a useful tool for visualizing badgeholder attestations and attestations at large. 

### Resources
- [Badgeholder EAS schema](https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b), 
  - I deployed a version of it on Goerli for experimentation [here](https://optimism-goerli-bedrock.easscan.org/schema/view/0x59631c889e2c1f9befae214d3aecf7e865d987cee5ff8c29ddbaa0b50010a34b)
- [RetroPGF round 3 voting badge distribution](https://gov.optimism.io/t/retropgf-3-voting-badge-distribution/6557) 
- [RetroPGF round 2 voting badge distribution](https://community.optimism.io/docs/governance/retropgf-2/#)
- [Get nerdsniped on attestations ](https://community.optimism.io/docs/identity/intro/)

**OP Labs or Optimism Foundation Contact**: Jonas (gh: @JSeiferth, TG/Discord: @jonassft)

## Possible Features
- **Basic**: Make changes to [coolgraph](https://github.com/smartcontracts/coolgraph) to display [badgeholder attestations](https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b) and host it to be available to users. 
  - If the `refferedMethod` is "badgeholderChoice", the source should be the `referredBy` address and the target the attestation recipient
  - if the `refferedMethod` is not badgeholderChoice, the source should be the `refferedMethod`(e.g. Foundation Choice, Past Badgeholder, Token House Elected or RetroPGF Recipient)
- **Extended**: Display how voting badges were distributed over multiple rounds (round 2 & round 3 + future rounds)
- **Extended**: Allow to discover the path of a specific voting badge - e.g. I can see how a specific badgeholder attained a voting badge and the relevant social graph 
- **Extended**: Display the [Optimist NFT](https://opensea.io/collection/optimist-nft) associated with each address
-  **SuperFeature**: Allow for the visualization of any attestation by enabling users to input any EAS Schema
- **SuperFeatureExtended**: Allow for the visualization of any attestation schema by enabling users to input any EAS schema and select arbitrary data fields to be visualized. 

## Impact
- This can help drive understanding in the Citizens' House of how badgeholders are selected
- This drives understanding of Optimism's identity layer 
- This could be the basis of a visual attestation explorer, a useful tool for users to interact with Optimism's identity layer

**Comment by xvoorvaa** [comment]
Oh this looks interesting, would love to work on this!

**Comment by mendesfabio** [comment]
hey, folks - how does the assignment for Ecosystem Project Ideas work? can you point me to any docs/links? just started to look into this and would love to contribute.

**Comment by xvoorvaa** [comment]
Base configuration is almost done. Just need few more days :)

**Comment by xvoorvaa** [comment]
I am back!

I finished the basics of the code:
https://attestation-visualizer.vercel.app/

Repo is still private, it has some sensitive info in there. Will be public in a few days...!

**Comment by Osas-dot** [comment]
Awesome let me know when it's public 👍

**Comment by xvoorvaa** [comment]
Hola! It is public :star2: 

https://github.com/xvoorvaa/attestation-visualizer

**Comment by Osas-dot** [comment]
Awesome!

**Comment by xvoorvaa** [comment]
@JSeiferth would you be able to make a few attestations that will be used in real scenarios?

You already talked about it in here:

> Basic: Make changes to [coolgraph](https://github.com/smartcontracts/coolgraph) to display [badgeholder attestations](https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b) and host it to be available to users.
> 
> If the refferedMethod is "badgeholderChoice", the source should be the referredBy address and the target the attestation recipient
> if the refferedMethod is not badgeholderChoice, the source should be the refferedMethod(e.g. Foundation Choice, Past Badgeholder, Token House Elected or RetroPGF Recipient)
> 
> Extended: Display how voting badges were distributed over multiple rounds (round 2 & round 3 + future rounds)

**Comment by JSeiferth** [comment]
@xvoorvaa 
1. What do you mean by creating attestations that will serve real-world scenarios? 
2. Only attestations that are issues by 0x621477dBA416E12df7FF0d48E14c4D20DC85D7D9 (Optimism multisig) are authentic, see the attestations we recently issued [here](https://optimism.easscan.org/schema/view/0xfdcfdad2dbe7489e0ce56b260348b7f14e8365a8a325aef9834818c00d46b31b)

**Comment by xvoorvaa** [comment]
Added some new features. It now looks pretty stable. I have a few more features I would like to add, what about you @JSeiferth ?
