### ISSUE TITLE
Delegate Mission Request: Builders grants program mission request

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#127]
### Delegate Mission Request: Builders grants program mission request

**Delegate Mission Request Summary:**
This mission request will allow the builders grants program that was run in previous seasons to continue in S5. This Mission Request focuses on continuing the builder’s grants process, as in seasons 3 and 4, to foster builder growth on OP Mainnet.

**S5 Intent:**
Aligned with Intent #2: Grow the Superchain

**Proposing Delegate:** Gonna.eth

**Proposal Tier:**
Ember

**Baseline grant amount:**
1.500.000 OP (50k OP Each)

**Should this Foundation Mission be fulfilled by one or multiple applicants:**
Multiple

**Start date:**
February 1st 2024

**Completion date:**
May 8th 2024

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=5e83531b-e091-4e7d-bc21-ed6ea67f212d)**

### Specification:

**How will this Delegate Mission Request help accomplish the above Intent?**
This request aims to advance builder growth and enhance the Superchain’s ecosystem by providing grants to projects deploying on OP Mainnet. The focus is on supporting initiatives that foster builder experience, tools, and applications within this domain.

**What is required to execute this Delegate Mission Request?:**

- Detailed proposals outlining initiatives to attract builders to Optimism must be submitted.
- Applicant projects should align with the goal of growing the Superchain’s builders base, specifically on OP Mainnet.
- Grant recipients will be accountable for executing proposed projects and delivering outlined milestones within the specified timeframe.

**How should the Token House measure progress towards this Mission?**

- Submission of comprehensive project plans requesting a grant for the grants council to review.
- Achieving project milestones as per the proposed timelines.
- Updates to the Grants Council on project progression at the end (12 months).

**How should badgeholders measure impact upon completion of this Mission?**

- Quantifiable increase in active builders deploying on OP Mainnet within the Superchain.
- Enhancement in developer tools or experiences resulting from the funded projects.
- Metrics showcasing the increased engagement and adoption of applications developed through these grants.

**Comment by bweick** [comment]
I'm confused are you looking to provide grants to people building as part of this request or providing grants to people to attract builders?

**Comment by opjulian** [comment]
These projects were selected for these mission requests 

https://app.charmverse.io/op-grants/community-builder-irl-age-of-empires-governance-platform-5307843531819139
https://app.charmverse.io/op-grants/easyretropgf-xyz-16908203122976806
https://app.charmverse.io/op-grants/page-6372885922099296
https://app.charmverse.io/op-grants/page-13415614066687764
https://app.charmverse.io/op-grants/page-7805364576656899
https://app.charmverse.io/op-grants/karma-gap-retropgf-project-discovery-and-impact-evaluation-008175679206510633
https://app.charmverse.io/op-grants/page-4129228981302593
https://app.charmverse.io/op-grants/namespace-47026143591884195
https://app.charmverse.io/op-grants/page-7128419920974485
https://app.charmverse.io/op-grants/xoptokens-enabling-xerc20-on-op-mainnet-messaging-layer-9043286328737232
https://app.charmverse.io/op-grants/page-13769815258717144
https://app.charmverse.io/op-grants/page-5782827753195403
https://app.charmverse.io/op-grants/radar-launch-future-pools-23476330616230623
https://app.charmverse.io/op-grants/migrate-inverter-network-10310452077197252
https://app.charmverse.io/op-grants/a-multichain-modular-privacy-framework-with-a-decentralized-compliance-network-4931843948755825
https://app.charmverse.io/op-grants/page-33341252653367004
https://app.charmverse.io/op-grants/ame-network-composable-social-network-8201927441390269
https://app.charmverse.io/op-grants/blockpi-account-abstraction-service-6499713590466969
https://app.charmverse.io/op-grants/bloom-metrics-the-optimism-impact-garden-8064181919524971
https://app.charmverse.io/op-grants/bonadocs-23948002871339513
https://app.charmverse.io/op-grants/building-an-on-chain-review-system-with-eas-745425000563134
https://app.charmverse.io/op-grants/dappbooster-frontend-starter-kit-5538923919258636
https://app.charmverse.io/op-grants/dappykit-superchain-42917102459787015
https://app.charmverse.io/op-grants/dark-forest-ares-2473027417469651
https://app.charmverse.io/op-grants/ethernaut-cli-5528017465072967
https://app.charmverse.io/op-grants/executable-an-intent-oriented-multi-tx-tool-011454040873412286
https://app.charmverse.io/op-grants/godot-engine-gdscript-sdk-for-connect-optimism-144384517023338
https://app.charmverse.io/op-grants/growthepie-application-level-analytics-for-the-superchain-250089520912399
https://app.charmverse.io/op-grants/in-depth-fee-tracker-for-op-chains-on-fees-growthepie-xyz-9750095618885746
https://app.charmverse.io/op-grants/page-528739678357524
https://app.charmverse.io/op-grants/namespace-7842790596987093
https://app.charmverse.io/op-grants/op-passport-9302219415326576
https://app.charmverse.io/op-grants/optimistic-crowdstaking-funding-more-builders-on-optimism-8173089535454674
https://app.charmverse.io/op-grants/polynomial-optimistic-indexer-1538697994300977
https://app.charmverse.io/op-grants/redprint-toolkit-an-interactive-code-generator-and-a-dev-framework-to-modify-deploy-opstack-s-contracts-9499729065142495
https://app.charmverse.io/op-grants/strands-optimism-integration-acceleration-6171257133376422
https://app.charmverse.io/op-grants/superchain-trading-tools-06248027711227655
https://app.charmverse.io/op-grants/tribuni-forum-proposal-alerts-summary-system-27035076138360314
https://app.charmverse.io/op-grants/unifra-open-infrastructure-for-everyone-9056352186275152
https://app.charmverse.io/op-grants/vain-an-open-marketplace-for-mining-vanity-eth-addresses-96344105785214
