### ISSUE TITLE
Delegate Mission Request: Growth and experiments grants program mission request

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#128]
### Delegate Mission Request: Growth and experiments grants program mission request

**Delegate Mission Request Summary:**
This mission request will allow the growth experiments grants program that was run in previous seasons to continue in S5. This Mission Request is dedicated to funding experiments and initiatives aimed at drawing more users to OP Mainnet, aligning with Intent #2: Grow the Superchain.

**S5 Intent:**
Aligned with Intent #2: Grow the Superchain

**Proposing Delegate:** Gonna.eth

**Proposal Tier:**
Ember

**Baseline grant amount:**
1.500.000 OP (150k OP each)

**Should this Foundation Mission be fulfilled by one or multiple applicants:**
Multiple

**Start date:**
February 1st 2024

**Completion date:**
May 8th 2024

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=b73c5d4e-11a0-4ddc-8f1b-d23a0f16a598)**

### Specification:

**How will this Delegate Mission Request help accomplish the above Intent?**
This request aims to catalyze user growth and engagement on Optimism by supporting experimental initiatives designed to draw more users onto the platform. The focus is on fostering adoption and activity across the Superchain.

**What is required to execute this Delegate Mission Request?:**

- Detailed proposals outlining experimental initiatives to attract users to Optimism must be submitted.
- Projects should align with the Growth Experiments Sub-Committee’s goal of maximizing user interaction within the Superchain.
- Grant recipients will be responsible for executing proposed experiments and delivering outlined milestones within the specified timeframe.

**How should the Token House measure progress towards this Mission?**

- Submission of comprehensive experimental plans within 6 month of grant allocation.
- Execution and completion of experimental milestones as per proposed timelines.
- Regular updates to the Grants Council on experimental progression on every milestone completed, highlighting user engagement metrics.

**How should badgeholders measure impact upon completion of this Mission?**

- Quantifiable increase in user activity and adoption of Optimism platforms as a result of the funded experiments.
- Enhancement in user experiences or engagement derived from the experimental initiatives.
- Metrics demonstrating increased user interaction and retention on Optimism.

**Comment by iSpeakNerd** [comment]
@opjulian I have a proposal to submit today, i was locked out of Charmverse before I could submit the application. would you please reopen for an hour?

**Comment by opjulian** [comment]
Hi @iSpeakNerd -- its best to direct any questions about the grants process to any of our incredible grants council members! Check out our designated channel in discord! https://discord.com/channels/667044843901681675/1069653708369047623

**Comment by iSpeakNerd** [comment]
ty for the reply @opjulian, ty posted there. no reply received

**Comment by opjulian** [comment]
These projects were selected for this mission request 

https://app.charmverse.io/op-grants/gearbox-protocol-22211914786751796
https://app.charmverse.io/op-grants/synthetix-growth-grant-request-4376972271806956
https://app.charmverse.io/op-grants/page-08553684013434348
https://app.charmverse.io/op-grants/velodrome-finance-growth-experiments-7649707564836516
https://app.charmverse.io/op-grants/pike-unlocking-the-multichain-utility-of-op-10175721236250412
https://app.charmverse.io/op-grants/proposal-silo-finance-7493304542273396
https://app.charmverse.io/op-grants/broaden-deepen-governance-token-user-base-5887478528357895
https://app.charmverse.io/op-grants/compound-finance-2527567543769036
https://app.charmverse.io/op-grants/debridge-2502174481807864
https://app.charmverse.io/op-grants/cobo-argus-optimism-defi-automation-platform-for-institutions-3528347400277536
https://app.charmverse.io/op-grants/page-26982954667926595
https://app.charmverse.io/op-grants/poolside-6891940389736264
https://app.charmverse.io/op-grants/supercharge-op-mainnet-8226050827659255
https://app.charmverse.io/op-grants/mountain-protocol-6319306937100639
https://app.charmverse.io/op-grants/page-26220924167927273
https://app.charmverse.io/op-grants/covenant-tradeable-debt-markets-backed-by-any-asset-48651255085780165
https://app.charmverse.io/op-grants/curve-lending-proposal-9157534743318139
https://app.charmverse.io/op-grants/gamma-strategies-growth-experiments-1787541707471647
https://app.charmverse.io/op-grants/page-011670432856976554
