### ISSUE TITLE
Delegate Mission Request: Incentivize Projects to Integrate the Farcaster Social Graph

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#137]
### Delegate Mission Request: Incentivize Projects to Integrate the Farcaster Social Graph

**Delegate Mission Request Summary:**

This mission request seeks to fund projects that enhance Superchain apps by using the social graph of Farcaster, the sufficiently decentralized social media protocol built on Optimism with over [50,000 users](https://dune.com/pixelhack/farcaster).

**S5 Intent**: 3 — Improve the consumer experience

**Proposing Delegate:** Layer3

**Proposal Tier:** Fledgling Tier

**Baseline grant amount:** 300,000 OP

The funding should be given to multiple projects with unique ideas on how to implement the social graph on their apps

Should this Foundation Mission be fulfilled by one or multiple applicants: Multiple

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=0154c436-2604-4309-b88f-bb833927c26f)**

### Specification
**How will this Delegate Mission Request help accomplish the above Intent?**

Going onchain is best experienced with friends. Unfortunately, modern day user experience can often times feel like a single-player game. By incorporating the Farcaster Social Graph on more projects, we incentivize users of those projects to join Farcaster, deepening and widening Optimism’s social graph and improving the consumer experience.

Examples:

Build trust in transactions by surfacing social network connections when paying users
Example: When I enter a user’s address to send them USDC, I am told if I ‘follow’ them via my social graph
This improves the consumer experience via a form of trust, because I am able to verify who I am sending money to
Integrate social discovery on an onchain platform
Example: An NFT platform could integrate the Farcaster social graph and display to a user “5 people you follow own this NFT”.
This improves the consumer experience by telling me what others are doing, which is a valuable way of driving more transactions
Develop a “Farcaster Toolkit” to allow users to create lists based on customizable inputs
Example: Build a front end where users go to a page and filter for farcaster users that follow limes.eth, are over 1 year old, and have an active badge. With that list I can drop custom NFT’s to those users
This improves the consumer experience by providing an easy way to collect social data
Provide matchmaking services based on who a user interacts with
Example: An onchain game can opt for a multiplayer experience that places them with first and second degree connections on Farcaster
Example: Games could create leaderboards that shows a user’s score compared against the people they follow on Farcaster
This improves the consumer experience by pairing users with people in their social circles

**What is required to execute this Delegate Mission Request?**

In order to accomplish the goals set forth above, the project(s) should have:

- An integration of Farcaster social data, such as follows, posts, reactions, and replies.
- Post transactions to the Superchain.
- Drive increased Superchain usage by leveraging social data.

**Please list responsibilities and/or expected deliverables:**

The goals of the teams applying for this grant should be:

- Launch a live project or feature deployed on the Superchain that uses Farcaster data.
- Demonstrate the traction it received after launching via Dune Dashboards.
- Open source the data collection mechanism for other teams to integrate.

**How should the Token House measure progress towards this Mission?**

- Usability and functionality of their social graph information, users should be able to see insights into their social graph outside of Farcaster
- In depth key product updates posted publicly in the Optimism Farcaster Channel
- Execution and completion of experimental milestones as per proposed timelines.

**How should badgeholders measure impact upon completion of this Mission?**

- Total number of transactions completed by users with Farcaster profiles.
- Volume of commercial activity (e.g., minting NFTs) from Farcaster users.
- Quality and novelty of the Social Graph integration

**Comment by chusla** [comment]
hello!  application here!  look forward to hearing back!

https://app.charmverse.io/op-grants/0xgraphix-working-title-37537920121474433

**Comment by opjulian** [comment]
These projects were selected for this mission request 


https://app.charmverse.io/op-grants/interested-fyi-building-new-social-graphs-on-farcaster-4293677372148865
https://app.charmverse.io/op-grants/daimo-08142527504624653
https://app.charmverse.io/op-grants/implement-farcaster-social-graph-data-into-colinks-and-cosoul-onchain-reputation-6222081767391467
https://app.charmverse.io/op-grants/alfafrens-3623619361574304
https://app.charmverse.io/op-grants/ponder-surveys-for-superchain-builders-43349586555154374
https://app.charmverse.io/op-grants/gridexplore-27975941097131307
https://app.charmverse.io/op-grants/speedtracer-5343696810950662
https://app.charmverse.io/op-grants/castpay-p2p-transaction-and-yield-earning-tool-on-warpcast-956190181927133
https://app.charmverse.io/op-grants/page-15106949611493015
https://app.charmverse.io/op-grants/noun-pcs-zynga-for-farcaster-7221383591291324
