### ISSUE TITLE
Delegate Mission Request: Deliver a Best-in-Class Perp Dex Mission Request

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#138]
### Delegate Mission Request: Deliver a Best-in-Class Perp Dex Mission Request

**Delegate Mission Request Summary:** This Mission Request is focused on developing and supporting a best-in-class perpetual decentralized exchange on Optimism. The goal is to offer a trading experience that rivals centralized exchanges in terms of performance, user experience, and feature set, thereby attracting more traders, liquidity providers, and users to the Optimism ecosystem.

The mission’s primary objective is to develop and support a Perps DEX on Optimism that competes with CEX perps, targeting the significant market gap highlighted by Binance Perps’ $30 billion daily trading volume compared to the $1-2 billion across all DEX perps protocols. This presents a substantial opportunity to attract users and capital to Optimism and support anchor protocols, which generate substantial economic value for the chain and generate sequencer revenue.

**S5 Intent 19: Intent 3:** Improve the Consumer Experience

**Proposing Delegate:** Matt

**Proposal Tier 16:** Begins at Fledging & scales up to tier of proposer.

**Baseline grant amount:** The Baseline grant amount for a project applying to this grant is 250k OP, with a max amount distributed for this mission set at 700k OP tokens. This amount has been determined as the required amount to support and incentivize a best-in-class perp dex effectively, which will migrate CEX users to DEX Perps.

**Should this Foundation Mission be fulfilled by one or multiple applicants:** Multiple.

**Start date:** ASAP

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=8c31e7c0-3a6a-4e5e-8eda-61a233e94b61)**

### Specification

**How will this Delegate Mission Request help accomplish the above Intent?**

Perpetual Futures DEX’s represent a critical segment in the cryptocurrency ecosystem, demonstrating substantial growth in user acquisition, trading volumes, and liquidity provider capital. Despite significant advancements in DeFi Perps, a considerable portion of crypto users continue to favor centralized exchanges for perpetual trading (30b in Binance Perps Volume daily vs 1-2b in DEX Perps volume). This preference underscores existing barriers within DeFi Perps, with complexities and perceived risks deterring potential users. This mission request is strategically designed to address and dismantle these barriers, offering robust incentives and fostering technological advancements crucial for transitioning users from centralized to decentralized perpetual trading platforms.

This mission will leverage the inherent strengths of perpetual DEXs to enhance the overall DeFi ecosystem on Optimism and the Superchain. By focusing on user experience improvements, account abstraction, and improved oracle integrations, we aim to bridge the gap between centralized and decentralized trading platforms. This will not only shift the current volume from centralized to decentralized exchanges but also create a robust ecosystem attracting and retaining capital within the Optimism network.

**What is required to execute this Delegate Mission Request?**

Technological upgrades in perpetual DEXs, including simplified trading interfaces, social logins, smart account usage and recovery, one-click trading options, expanded collateral and margin options, MEV-resistant order settlement and liquidations, off-chain decentralized oracle usage, and more.

- Enhance user onboarding processes, including integration with bridges, account abstraction and smart wallet usage, to streamline user experience.
- Key focus on risk management to ensure delta neutrality for LPs and deep liquidity for traders while supporting major and long-tail pairs.
- Open-source standards to support long-term development of innovations around Perp Dexs.
- Deployment of OP incentives to encourage sustained LP and Trader Migration focused on gas rebates, bridge rebates, developer incentives, and trading fee rebates.

**How should the Token House measure progress towards this Mission?**

- Tracking the implementation of technological improvements and user experience enhancements.
- Monitoring the volume of capital migration from Mainnet/CEX/etc to the DEX and its retention rate.
- Evaluating the increase in trading volumes, active users, LP capital flow.

**How should badgeholders measure impact upon completion of this Mission?**

- Assessing the growth in daily and monthly trading volumes compared to baseline figures.
- Analyzing the increase in the number of active users and the expansion of the user base.
- Reviewing feedback from users regarding the trading experience and user interface improvements.
- Analyzing the flow of LP capital which will be used to support Perp DEX’s compared to baseline figures.

**Comment by twizzworld** [comment]
I will apply to this. I am passionate and can complete the mission.

**Comment by opjulian** [comment]
These projects were selected for this mission request 

https://app.charmverse.io/op-grants/synthetix-mission-request-for-perps-dex-18198593785543293

https://app.charmverse.io/op-grants/velodrome-finance-perp-dex-5323596864442492
