### ISSUE TITLE
Delegate Mission Request: An Optimistic Future for Art

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#139]
### Delegate Mission Request: An Optimistic Future for Art

**Delegate Mission Request Summary:**
Onboard more artists, collectors, and patrons to Optimism by exhibiting the power of art on Optimism during multiple satellite events during major Crypto, Art, or NFT conventions. This can be accomplished by exhibiting W❤️TA contest winners. Hosting open calls to incentivize the onboarding of artists on the Superchain with exhibition spots. Encouraging attendees to mint Artwork and participation tokens.

**Intent:** 3 - Improve the Consumer Experience

**Proposing Delegate:** [Brichis 1](https://vote.optimism.io/delegate/brichis.eth) (Sponsor)

**Proposal Tier:** Ember

**Baseline grant amount:** 15k OP (5k OP per applicant)

**Should this Foundation Mission be fulfilled by one or multiple applicants:** Up to 3

**Completion date:** By the end of the year 2024

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=f3b4af8b-1eac-4c18-982a-081bc55e17bd)**

### Specification

**How will this Delegate Mission Request help accomplish the above Intent?**

Displaying the W♥️TA winners and the success they achieved in securing funds for their artwork will enhance the impact of the contest and establish a benchmark for what Optimism can achieve for artists, particularly for those who are not yet aware. Showcasing the art at physical exhibitions during major events offers the optimal experience for patrons and collectors to engage with the artists. There’s a remarkable opportunity to organize an event with an open call, which will introduce both artists and users to Optimism. This can create a dynamic social cycle where collectors meet artists and can effortlessly and accessibly acquire all the exhibited artwork. Ultimately, this approach will attract creators who will in turn bring in the next wave of collectors and patrons, while also providing them with tangible proof of their attendance at the exhibit. Each event can add on additional activations like an online counterpart to the in person event. This allows the curated exhibition to live on forever. On site contests can be hosted to encourage artists attending the event to participate in a competition.

**What is required to execute this Delegate Mission Request?**

- A venue to host the events.
- Screens for the exhibition of art.
- A videographer to document the event and produce additional content, such as collectibles and rewards associated with the event.
- Coordination and curation of artist onboarding on the OP Mainnet.
- Creation of attendance tokens to facilitate the onboarding of attendees.

**How should the Token House measure progress towards this Mission?**

- Organizing a side event during major Crypto, Art, or NFT conventions.
- Generating and disseminating Social Media content to promote the event.
- Holding a press conference to promote the event.
- Creating an after-movie and compiling photographs of all exhibited art for provenance documentation and inclusion in artists’ portfolios.
- Delivering a comprehensive report one month post-event, detailing metrics from artwork and attendance token mints.

**How should badgeholders measure impact upon completion of this Mission?**

- The total count of attendance mints.
- The amount of ETH generated for artists who were onboarded to the OP Mainnet.
- The number of contracts deployed on the OP Mainnet (NFTs from artists)
- The count of new wallets created on the OP Mainnet from people who physically attended the event.
- The number of attestations/NFTs issued to artists encouraged to mint on the OP Mainnet.
- The number of attestations/NFTs distributed to event attendees.
- The total amount of fees generated through the event.

**Comment by LainVisione** [comment]
I guess this Is my kind of mission 🔴🚀
Will gather a team 4 start x

**Comment by opjulian** [comment]
These projects were selected for this mission request 


https://app.charmverse.io/op-grants/audio-galleries-48394010617808436
https://app.charmverse.io/op-grants/page-49337110542685325
https://app.charmverse.io/op-grants/page-752387536271468
