### ISSUE TITLE
Delegate Mission Request: Governance Mentorship Program Mission Request

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#146]
### Delegate Mission Request: Governance Mentorship Program Mission Request

**Delegate Mission Request Summary:**
A program that pairs experienced governance participants with newcomers to transfer knowledge, offer guidance, and encourage active participation.

**S5 Intent: Intent 4:** Improve governance accessibility

**Proposing Delegate:** [DAOStewards 9](https://vote.optimism.io/delegate/0xc2490D220419ACdCeD68428Ac413c8483d08D1AB)

**Proposal [Tier 5](https://gov.optimism.io/t/collective-trust-tiers/5877):** Fledgling Tier

**Baseline grant amount:** 40,000 OP

**Should this Foundation Mission be fulfilled by one or multiple applicants:** up to 4

**Start date:** Asap

**Completion date:** 30/05/2024

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=2ee526f2-20a1-4cfc-9fcb-12035ab45f40)**

### Specification

**How will this Delegate Mission Request help accomplish the above Intent?**

This Delegate Mission Request will help accomplish the above Intent by creating a Governance Mentorship Program (GMP). The GMP will provide a variety of sessions to suit different audience types to help them understand the complexities of governance, the significance of proposals, and how their individual contributions matter. This personalised approach can help demystify governance processes, making them more approachable for individuals who may feel overwhelmed by the technicalities or scale of governance systems. The GMP will also focus on engaging underrepresented groups within the Optimism community, ensuring that these voices are not just heard but actively involved in governance decisions. Special workshops, AMA sessions, and community calls could be conducted in various languages, considering the cultural diversity within the ecosystem. By encouraging a broader range of community members to engage in governance, the collective decision-making process could be enriched with a multitude of perspectives, leading to more balanced and considerate outcomes. The program can have targeted efforts to incorporate views from different demographics, professions, and geographic locations.

**Please explain alignment with the relevant Intent**

In order to prioritize accessibility of Governance systems to newbies, or in general to any new field or area of expertise, it’s often advised to find a mentor who has already gone through the process to help newbies get up to speed quickly and avoid spending time repeating mistakes from the past. Based on this principle, the GMP aims to increase the understandability of the governance system for new entrants as well as enable governance veterans to understand the pain points of newbies in a much more intimate way. This not only helps newbies, but the experience that veterans gain can be leveraged in the upcoming season to craft better solutions to increase accessibility.

**The main objectives of this program are:**

- Increase Governance Participation
- Educational Focus
- Develop New Active Delegates

**What is required to execute this Delegate Mission Request?**

- Identify experienced community members who are willing to participate in the GMP.
- Develop a curriculum that covers the complexities of governance, the significance of proposals, and how individual contributions matter.
- Create a schedule for one-on-one sessions, workshops, AMA sessions, and community calls.
- Identify underrepresented groups within the Optimism community and reach out to them to encourage participation.
- Conduct periodic surveys and feedback sessions to improve the program

**Please list responsibilities and/or expected deliverables**

- Each submission should include a comprehensive curriculum which is targeted towards a demographic, profession, or people from specific geographic background
- A background of the delegate along with links to relevant experience and background in the field of governance and mentorship
- A report on the overall mentorship program and the impact it created at the end of the mission
- The course should include these minimum deliverables, but delegates are free to innovate on top.

Understanding the Optimism Collective

Introduction to the mission, structure, and functions of the Collective.
In-depth exploration of the Optimistic Vision and RPGF
Overview of public goods and their significance in the Optimism ecosystem.

Understanding OP Mainnet and OP Stack: The technical foundations of the Superchain.
Basics of Optimism Governance

An overview of the five entities constituting the Collective.
Detailed insights into the Token House and Citizens House.
Comprehension of governance processes and responsibilities.
Forum Engagement and Policies

Effective navigation and participation in the Optimism Forum.
Familiarization with Optimism’s policies and codes of conduct.
Practical guidance on initiating governance participation.
Grants in Optimism

Understanding the functioning and types of grants in Optimism.
Guidelines for grant application processes.
Proposals, Feedback, and Voting,

How to read, understand, and evaluate proposals.
Best practices for providing feedback and creating impactful proposals.
How to delegate your OP to a good delegate.
Insight into voting cycles, seasons, and active participation in voting.
RetroPGF
Evaluating Impact
Delegate Decision-Making Insights

Assessment and engagement

The following activities are suggested by this mission request, however delegates are free to innovate around these ideas.

- Onchain proof: Participants will receive attestations upon completion of each class, underscoring their learning and involvement.
- Interactive Quizzes: At the end of each workshop, interactive Kahoot quizzes or tailored questionnaires will be provided. These assessments are designed to evaluate the participants’ understanding and knowledge acquisition from each session.
- Practical-activity: At the end of most workshops, participants are required to undertake a governance activity, to apply its knowledge.
- Incentive mechanism: Accepted participants that attend at least 75% of the sessions and successfully complete the activities will be compensated 100 OP. This ensures commitment and maximizes the likelihood of effective learning and active participation in governance.

**How should the Token House measure progress towards this Mission?**

- Number of participants who attended and completed the activities.
- Number of participants who reported an increase in understanding of governance processes.
- Number of participants who received scores above a certain threshold
- Feedback from participants on the effectiveness of the GMP

**How should badgeholders measure impact upon completion of this Mission?**

- 
- Number of participants who completed the GMP.
- Number of participants who reported an increase in understanding of governance processes.
- Number of participants who reported feeling more comfortable participating in governance decisions.
- Feedback from participants on the effectiveness of the GMP

**Comment by Chakerbijo** [comment]
Cool

**Comment by opjulian** [comment]
This project was selected for this mission request 

https://app.charmverse.io/op-grants/govtalks-unlocking-optimistic-potential-2957594524260736
