### ISSUE TITLE
Delegate Mission Request: Delegation Quest SDK Mission Request

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#147]
### Delegate Mission Request: Delegation Quest SDK Mission Request

**Delegate Mission Request Summary**

This initiative aims to continue the development of open-source infrastructure for the Optimism Collective towards strategically enabling the governance-related incentives to achieve objectives of: increasing OP votable supply, increasing active OP delegations, and rewarding beneficial delegate behavior (including participation and involvement).

**S5 [Intent 1](https://gov.optimism.io/t/collective-intents-season-5/6883) Please list the Intent your Request aligns with here:**
[Intent 4: Improve Governance Accessibility](https://gov.optimism.io/t/collective-intents-season-5/6883#intent-4-improve-governance-accessibility-5)

**Proposing Delegate:**

Rabbithole
Proposal [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877):

**[Fledgling](https://gov.optimism.io/t/collective-trust-tiers/5877#fledgling-tier-eligible-to-receive-up-to-250k-op-3)
Baseline grant amount:**

200,000 OP

**Should this Foundation Mission be fulfilled by one or multiple applicants:**
Multiple

**Start date:** ASAP

**Completion date:** 8/31/2024

**[Apply Here](https://app.charmverse.io/op-grants/proposals/new?template=0f1b2f76-caf3-42d6-bbf8-a2952d540227)**

### Specification
**How will this Delegate Mission Request help accomplish the above Intent?**

The requested mission seeks to create an open-source infrastructure tailored for governance purposes, aimed at facilitating governance-related incentives. Its central role is to foster the growth and development of the Optimism Collective. Moreover, it is intended to build upon previous [Optimism delegation research 6](https://www.gsb.stanford.edu/faculty-research/working-papers/what-kinds-incentives-encourage-participation-democracy-evidence) to lay a robust groundwork for governance incentives, particularly to enhance the expansion of the Token House.

The mission will pave the way for innovative governance experiments, educational initiatives, and possibly even a new range of governance-centric products and services, all developed utilizing the open-source infrastructure. In deploying this open source SDK, we believe that we can make a large impact in a rather unexplored area of governance incentives, and hopefully pave the way for others to build and iterate upon governance design expirementations/iterations implementations in a permissionless, decentralized environment.

**Please explain alignment with the relevant Intent**

The mission proposal is strategically aligned with Intent #4: Enhance Governance Accessibility. Its fundamental objective revolves around the provision of specialized tooling and infrastructure designed to implement incentives, with a clear goal of expanding the votable supply of OP.

Furthermore, the open-source nature of the SDK underpins this mission’s objective to motivate developers to engage with these tools for executing various controlled governance experiments. By concurrently supporting governance incentives and tool development, we are confident that this mission will significantly influence governance contributors, researchers, and the evolution of future tooling. This initiative is anticipated to have a direct and meaningful impact on the ease of governance participation on the OP mainnet.

**What is required to execute this Delegate Mission Request?**

- Development
- Plug-ins
- Frontend
- Campaign Planning
- Partnerships and Marketing Coordination
- Promotion of Quests and DAO
- Quest Design and Coordination
- Delegation Campaign
- Quest Operations
- Promotion
- Campaign Analysis and Retrospective

**Please list responsibilities and/or expected deliverables**

Deliverable 1: Open Source quest plugins with built-in governance incentivization enabled (i.e. [Agora Quests 8](https://terminal.rabbithole.gg/quests/f7b6b464-b7ec-4b7d-8561-7fe71049d3f3)). Anybody will have the ability to deploy a frontend to support governance-based quests on OP Mainnet, add support of governance-based quests to their existing frontend, or deploy quests.

Plug-in development includes:

Allowlist capabilities enabling supporting delegation to one-of-many delegate addresses (rather than just one target address)
Vote Plug-in Action Type
Frontend development includes:

Creation of a quest or incentive gateway for users.
Deliverable 2: One month of concurrent campaigns comprising:

Governance quest rollout which includes incentives for:
Delegates
Customizable quest parameters enable quests incentivizing further governance power distribution (ie incentivize delegator diversity)
Delegators
New/Existing
Historically Active Governance Participants
Campaign Examples:
New Delegations Campaign: Target new delegators to delegate OP.
Claimer Delegation Campaign: Target all OP incentive claimants to delegate to delegates.
Re-Delegation Campaign: Target current delegators to inactive delegates to re-delegate to Active Delegates.
Collaborative co-marketing events in which ecosystem stakeholders and protocols can educate the broader ecosystem on delegation, funneling new delegates → incentives:
Twitter spaces
Deliverable 3: Data and analytics, including a project-specific Dune Dashboard.

**How should the Token House measure progress towards this Mission?**

- Quest contracts deployed: n/n
- Quest governance parameters enabled: n/n
- Collaborative governance marketing event announced: 1/1
- OP quest incentives deployed: n/n
- OP delegated via quests: n/n

**How should badgeholders measure impact upon completion of this Mission?**

- Quest creators: quest contract deployments.
- Quest completions: claims from contracts.
- Delegators: number of delegators sourced via quests.
- Delegated OP: cumulative number of OP delegated via quests.
- Quest incentive RoI: increase in governance metrics as a ratio of costs to incentivize.

**Comment by sleeper12go** [comment]
gg

**Comment by Babaronica** [comment]
Super cool

**Comment by Chakerbijo** [comment]
Cool
