### ISSUE TITLE
Foundation Mission Request: Expanding support for developers in the Collective through TechNERDs [CONTRIBUTION]

### ISSUE THREAD

**Issue by Nicca42** [ethereum-optimism/ecosystem-contributions#151]
## **Foundation Mission Request - Expanding support for developers in the Collective through TechNERDs** 
*Expand [existing support](https://github.com/ethereum-optimism/developers/discussions) for the Optimism Collectives developers by increasing the number of techNERDs. This allows developers to build faster and with less frustration (as they can get help easily!) helping make Optimism the obvious choice. This mission would cover rewards for up to 10 TechNERDs until the start of Season 6. It will not cover training, though [resources are provided](https://github.com/ethereum-optimism/developers/tree/main/community/support/training). Apply [here](https://optimismfnd.typeform.com/techNERDs-app).* 

* **S5 [Intent](https://gov.optimism.io/t/collective-intents-season-5/6883):** *Technical Decentralization*
* **Proposal [Tier](https://gov.optimism.io/t/collective-trust-tiers/5877):** [*Fledgling*](https://gov.optimism.io/t/collective-trust-tiers/5877)
* **Baseline grant amount:** 8,125 OP per TechNERD (for 15 active weeks, min 6 active weeks)
* **Should this Foundation Mission be fulfilled by one or multiple teams:** *Multiple*
* **OP Labs or Optimism Foundation Sponsor: @Nicca42 - Foundation**
* **Last Submission by:** 9 May 2024 (end of S5)
* **Selection by:** Rolling acceptance until submission deadline.
* **Start date:** 11 Mar 2024
* **Completion date:** 27 Jun 2024 (start of S6)

---

## **How will this Foundation Mission Request help accomplish the above Intent?**

Technical Decentralisation needs to include decentralising support, allowing the developer community to help itself. The TechNERD program enables this by decentralising the knowledge needed to debug, build, and deploy on the Superchain. This Mission will expand the number of TechNERDs, with a focus on covering the major timezones (South/North America, Europe/Africa, Asia, Oceania). 

By the start of S6 all major timezones should be covered, allowing developers across the world and the Superchain to have fast and reliable help in their development journey. This mission will also decrease the turnaround time from [developer support requests to resolution](*https://github.com/ethereum-optimism/developers/discussions*).

## **What is required to execute this Foundation Mission Request?**

TechNERDs will need to:
- Maintain a minimum of 6 active weeks. Only active weeks are considered for rewards. Active weeks are defined as:
    - At least 3 tickets answered per week OR 3 [points (T-shirt sized)](https://github.com/ethereum-optimism/developers/blob/main/community/support/brainstorming-sessions/02-brainstorming-session.md). See the [support metric tracking](https://github.com/ethereum-optimism/developers/blob/main/community/support/metrics/README.md) for more information.
    - Minimum of 25 messages a week in the Optimism Discord.
- Create/update a [“Contributor” page](https://github.com/ethereum-optimism/developers/tree/main/community/support/technerd-program/contributors) in the support repo.
- Attend TechNERD bi-weekly calls. 

## Please list a [critical milestone](https://gov.optimism.io/t/token-house-grant-policies/5833). 
The critical milestone should be a measure of whether an applicant has made best efforts to execute what is outlined in this proposal or not. If an applicant fails to achieve the critical milestone, their grant may be clawed back.

- *Contribution activity increase on the [technical support repo](https://github.com/ethereum-optimism/developers/graphs/community?period=last_3_months) from S4.*
- *Consistant contribution activity within [developer channels in the optimism Discord](https://discord.com/channels/667044843901681675/1080862392281481246) (developer messages get replies within 12 hours).*
- *Decrease the time from questions asked in the [Technical support repo](https://github.com/ethereum-optimism/developers/discussions) till an answer is submitted (compared to S4).*

## **Who from your team will be working on this Mission Request?** 

- *@Nicca42 - Program management & maintenance, filtering of applications & ensuring consistency with other Contribution Paths.*
- *@[sbvegan](https://github.com/sbvegan) - Managing contributors, escalating discovered issues, ensuring contribution minimums are met.*

## **How should the Foundation measure progress towards this Mission Request?**  
Token House milestones are mostly about accountability, so they should measure progress towards completion. 

- *All major timezones are covered by at least one TechNERD (South/North America, Europe/Africa, Asia, Oceania).*
- *Compared to before this Mission turnaround time on Discussions decreases by 10%. Current time to (accepted) answer is 5 days.*

## **How should badgeholders measure impact upon completion of this Mission (RFP)?** 
These should be focused on performance and may be used by badgeholders to assess your Misson’s impact in the next round of RetroPGF.

- *Contributor data from the [developer support repo](https://github.com/ethereum-optimism/developers/graphs/community).*
- *Testimonials from developers helped by the program.*
- *Contributions from TechNERDs to the monorepo and other core infrastructure repositories will be tracked.*
- *Quality of discussions and answers in the [technical Support repo](https://github.com/ethereum-optimism/developers/discussions).*

## Application instructions

Apply [here](https://optimismfnd.typeform.com/techNERDs-app). Applications are accepted on a rolling basis until the last submission date.

**Comment by Chakerbijo** [comment]
Cool

**Comment by ngerald51** [comment]
Hi there, i have applied as well. How will we know whether we are being accepted in this program?
