### ISSUE TITLE
📝 Draft Project Idea: Impact Evaluation Indexer

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#16]
**What is a Draft Project Idea?**

A Draft Project Idea is a concept for a project within the Optimism ecosystem that is generally considered valuable but has not yet been fleshed out into a clearly defined product. Draft Project Ideas may be converted into Ecosystem Project Ideas as they are explored further and more thoroughly specified.

---

## Summary
 
This is a subset of indexers in general. It'd be great to have a dedicated indexer that generates measurements of the impact of user behavior onchain. Think of this like a mix between an indexer and an algorithm that assigns value to certain user actions. Who are the most "impactful" users on chain?

## Possible Features

- Build on top of other indexers or build your own
- Create an algorithm that scores user impact onchain

**Comment by mostafalarki1368mos** [comment]
/https://gov.optimism.io/t/welcome-to-the-optimism-collective-discourse/7/5[](url)

**Comment by Ashutosh7700** [comment]
h
