### ISSUE TITLE
🔴 Ecosystem Project Idea: Decentralized PGP Key Server

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#17]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Use attestations to create a decentralized [key server](https://en.wikipedia.org/wiki/Key_server_(cryptographic)) for [PGP keys](https://en.wikipedia.org/wiki/Pretty_Good_Privacy). For instance, make it easy for users to attest that a public key is valid, and display a trust score for that key’s validity. This creates a [web of trust](https://en.wikipedia.org/wiki/Web_of_trust) model between users and their public keys.

## Possible Features

- Allow users to easily attest to the validity of a PGP key
- Create a trust score based on attestations between keys
- Check the trust score for a given key

**Comment by positonic** [comment]
Sounds cool, can you give an example of an application or individual who might use such an implementation that would serve as a good use case to build against?

**Comment by positonic** [comment]
In a world of end to end encrypted messenger apps, what is a major problem that needs to be solved? 

File storage encryption? Is email still a major usecase? Who can we imagine as a first integrator?

**Comment by sambacha** [comment]
fwiw, you can use SSH keys for signing, and github lets you query both SSH and GPG keys for users:

e.g.

```console
$ curl https://github.com/sambacha.keys

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDum/h6hed1830Ceci7C9CDycshyU9Yig05c/HD4R+YgyUwVrKvxGOLgLcH4LwKuNBCInP2HAYs7gAWdIusc3/vBzgdh1W9cRydCArbJg2/4MJYF8iA7PZ3th8geiLzJXjEGk9hnntQEW3qnM2lSDEx1oc6Z9UJOarhYDhiISZA4BpFNw4dqwfG3CvmBNDGmWzq9z1HQo14l6g7lCJRHkkYhRJI0IqKWo15lwnx0AHh6qPgJssNfuTKVsmT8/7uUKS6+MheY1fM786VGpLIsBO5wcagYoTt4fEj878/ewbxaUbSx3TU78iwTC+3UlRrLMxAMKAQW85tKZT1m5P717jEoj80dPFlFIEsuIiQCPZ5o9fewJWc+Zy2TBYw/T+1HJdJm5nxeFQi59eZKG5xapEBX9rMxa5YXAV+uhhGpR/oIiEs8YlfOUUYsQwgbcI5U8E+9Os285FoeBKUf7grOIlKGPvGhq25LHAoHH8Sm/y0D6qxDd2L7zP8wz24c8acYZE=
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGm7E1J63Vo08WVPhh2ht8LwP4mJtx6F27eBwbUoRwkh
```

```console
$ curl https://github.com/sambacha.gpg

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEY7aRHRYJKwYBBAHaRw8BAQdABrNhJQeR47SgP5NLBxGIBS6a8qBJJW+EPkYB
/hBFpYW0I1NhbSBCYWNoYSA8c2FtQG1hbmlmb2xkZmluYW5jZS5jb20+iJYEExYI
AD4WIQRjgWeohT1yjdPefvwnABbcibkljAUCY7aRHQIbAwUJB4TOAAULCQgHAgYV
CgkICwIEFgIDAQIeAQIXgAAKCRAnABbcibkljFeRAP0SgKLujZAYkDXrEnaYDAcH
I0xb2ompqHwfFvkMjAh2owD/R5FpWheIHHvONgv7gTU/N8DzyTpYTKxdlBUMu9ge
RgK4OARjtpEdEgorBgEEAZdVAQUBAQdAUFJpKoR8Sb9/D2gJaTw1PfnfeoOHuyqF
OKy/nLkqAWgDAQgHiH4EGBYIACYWIQRjgWeohT1yjdPefvwnABbcibkljAUCY7aR
HQIbDAUJB4TOAAAKCRAnABbcibkljKUZAQCeI1Eqz9rgHVRW8sMlb7/wTi3SmNd8
+uj9EI3mWS+xtwEAtJQpolYVRCVJmQtk98m9Yfn9WPUD+Z5TDITLvqtERQI=
=iDA0
-----END PGP PUBLIC KEY BLOCK----
```

**Comment by koisose** [comment]
@smartcontracts i think @humanprotocol already create something like this https://dashboard.humanprotocol.org/kvstore but i think they havent deploy it for optimism blockchain https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md

**Comment by theresa-whynot** [comment]
@smartcontracts If I have a team who wants to pursue this, how would I go about getting this from 'open' to an 'in progress' status? Thanks!
