### ISSUE TITLE
🔴 Ecosystem Project Idea: Universal Message Passing Interface

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#18]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Define a message passing interface that allows for universal communication between any two EVM-based blockchains. Should come with examples that demonstrate how messages are passed and how systems can deal with messages that have different security models.

## Possible Features

- Allow users to pass messages between any two EVM-based blockchains.
- Allow users to deal with different security models.

**Comment by sajet006** [comment]
We have been working on this on our SuperHack project.
We have defined a universal message passing interface that works with:

- LayerZero
- Hyperlane
- Chainlink CCIP
- Axelar (soon)

We are using the Diamond standard which allows us to be much more flexible and upgradable to add more bridges in an iterative process. Each Bridge will have its own facet.

Users will be able to select which ever bridge they want to use.

### Functionality
Our Project allow users to call functions on the destination chain as well as pass a parameter into it.
For example a user can the Mint function by passing the Mint(20) as the parameter. This will call the mint function with the parameter as 20.

### Security models:
We at the moment have worked on two security modes
**Without Acknowledgement:** Users can all any function with parameters on the optimism network.
**With Acknowledgement:**  Users can call a function with parameters on the destination chain and once executed an acknowledgement will be sent back to the source chain to confirm that the function on the destination has been executed. Optionally another function call can be executed on the source chain as the acknowledgement is receive. This is the call back function.
**Callback Function:** The callback function is an optional function which is called with the acknowledgement. It can be used to run any arbitrary logic. For example, You can call Mint(20) on the destination chain and as you receive the acknowledgement you can call the call back function to update the total supply.
### Architecture diagram
![Cross Carat](https://github.com/ethereum-optimism/ecosystem-contributions/assets/41197088/595b0065-ebe1-4e5b-a9eb-a14038c60dbb)

**Comment by OpGammer11** [comment]
I wanted to work on this, any body doing it already?
@sajet006
