### ISSUE TITLE
Delegate Mission Request: Develop non-technical solutions for increasing both voter and token participation in the DAO 

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#203]
# Delegate Mission Request: Develop non-technical solutions for increasing both voter and token participation in the DAO 

###  [Application Link](https://app.charmverse.io/op-grants/proposals/new?template=1a12736e-c025-4cb5-8cad-2ae53a46a950)

Make sure you’re logged in with Farcaster, and make sure you choose the correct S6 Mission field (this will be the same name as the title of this Mission Request). 

If you're having trouble joining the Optimism Grants Council space, join via this [invite link](https://app.charmverse.io/invite/5e28cc).

--- 

**Delegate Mission Request Summary**: Develop non-technical solutions for increasing both voter and token participation in the DAO.

**S6 Intent**: Progress Towards Decentralization

**Proposing Delegate/Citizen**: @kaereste on behalf of Event Horizon DAO (EventHorizonCommunity.eth)

**Total grant amount**: 75k OP

**Should this Mission be fulfilled by one or multiple applicants**: Multiple

**How will this Mission Request help accomplish the above Intent?**:

As outlined in [Missions v2.5](https://gov.optimism.io/t/season-6-missions-v2-5/8106), mission requests should contribute to target metrics. In the case of [Intent 1](https://vote.optimism.io/proposals/46662599590868619415724059715206858415123913604990481279137083354870809650669), that’s “Token House governance: Increase votable supply by 15% to 100M OP”. The above Mission Request is therefore in line with this north star by placing an emphasis on bringing in both new voters and tokens.

**What is required to execute this Mission Request?**

While contracts and technical developments may be included, the solution will be expected to create an improvement mechanism for citizen voter participation, voice amplification, and inclusion primarily through non-technical means.

The solution team or individual will be expected to…

* Provide a detailed rationale for their approach with a clear depiction of how and why their solution will drive the impact metrics detailed below.
* Build all required components of their solution
* Maintain their solution product or offering for a minimum of 12 months including all needed adjustments, additions, or other maintenance work needed to keep the solution viable and available for the community.
* Capture relevant metrics as they pertain to achieving the desired intent for public disclosure to the community.

**How should governance participants measure impact upon completion of this Mission?**

* **Milestones:**
  * The solution will be subject to the typical milestone-based delivery and assessment process. The Milestones and Metrics committee will assess the completion of milestones, as usual.
* **Metrics**:
  * Increase of total votable supply of OP, highlighted as a core metric in [Intent 1](https://vote.optimism.io/proposals/46662599590868619415724059715206858415123913604990481279137083354870809650669)’s ratification
  * Increase in number of voters in Optimism DAO
* **Impact**:
  * Impact will be measured by the absolute and relative performance of the aforementioned two metrics, both in line with the key metric of [Intent 1](https://vote.optimism.io/proposals/46662599590868619415724059715206858415123913604990481279137083354870809650669).

**Has anyone other than the proposer contributed to this Mission Request?** No

## Which metric will the success of this Mission Request be evaluated against?

The North star metric against which this Mission Request should be evaluated is **# of addresses delegated for the first time,** as it reflects how this effort lowers the barriers to governance participation. This metric was suggested by the foundation and approved by the Grants Council.

**Comment by iunknow588** [comment]
A question here. 
"Has anyone other than the proposer contributed to this Mission Request? No."

May I  ask , if this implies that the proposer has already achieved it?

**Comment by opjulian** [comment]
Hi @iunknow588 -- please head to our discord and ask this question to our grants council. You can tag them @ grantscouncil with any delegate mission request related questions!

**Comment by iunknow588** [comment]
> Hi @iunknow588 -- please head to our discord and ask this question to our grants council. You can tag them @ grantscouncil with any delegate mission request related questions!

Hi, opjulian，Thank you very much, I will go and check it...
