### ISSUE TITLE
Delegate Mission Request: Grants Claiming Tool

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#205]
# Delegate Mission Request: Grants Claiming Tool

###  [Application Link](https://app.charmverse.io/op-grants/proposals/new?template=1a12736e-c025-4cb5-8cad-2ae53a46a950)

Make sure you’re logged in with Farcaster, and make sure you choose the correct S6 Mission field (this will be the same name as the title of this Mission Request). 

If you're having trouble joining the Optimism Grants Council space, join via this [invite link](https://app.charmverse.io/invite/5e28cc).

--- 

**Delegate Mission Request Summary**

Develop a tool for claiming grants in a way that drives delegation and supports the governance process, enhancing the decentralization of the Collective. The system has to consider approvals from The Grants Council and The foundation and have a clawback option.

**S6 Intent**

1: Progress Towards Decentralization

**Proposing Delegate/Citizen**

Gonna.eth

**Total grant amount**

100.000 OP

**Should this Mission be fulfilled by one or multiple applicants**

Up to 2

**How will this Mission Request help accomplish the above Intent?**

This mission request will help accomplish the Progress Towards Decentralization intent by creating a tool for claiming grants that drives delegation and supports the governance process. This tool will incentivize delegates to actively participate in the governance process and drive the delegation of votable supply to a broad range of stakeholders, leading to greater decentralization and transparency in the Collective.

**What is required to execute this Mission Request?**

1. Define the requirements for the grants claiming tool, including user interface, data storage, and data retrieval mechanisms.
2. Design and develop the tool architecture, including integration with existing Collective infrastructure.
3. Implement the tool, including testing and quality assurance.
4. Deploy the tool and provide documentation and training/tutorials for users.
5. Monitor and evaluate the effectiveness of the tool in driving delegation and supporting the governance process.

**How should governance participants measure impact upon completion of this Mission Request?**

Governance participants can measure the impact of this mission request by tracking the following metrics:

1. Number of grants claimed using the new tool.
2. Increase in delegation driven by the tool.
3. Improved participation and engagement in the governance process.
4. Increase the number of unique delegators using the tool.

**Milestones**

1. Requirements definition completed 
2. Tool design and architecture completed 
3. Tool implementation and testing completed 
4. Tool deployed and integrated with Collective infrastructure
5. Evaluation and monitoring of the tool's effectiveness completed 

**Impact and Metrics**

1. Number of grants claimed using the new tool.
2. Increase in delegation driven by the tool.
3. Improved participation and engagement in the governance process.
4. Increase in the number of unique delegators.
5. Number of clawbacks executed using the new tool.

## Which metric will the success of this Mission Request be evaluated against?

The North star metric against which this Mission Request should be evaluated is ***total amount of OP delegated from new addresses using the grantee’s protocol*,** as it helps assess the aggregated effect that this initiative has on the total votable supply. This metric was suggested by the Foundation and approved by the Grants Council.

**Comment by Immanuel-john** [comment]
hi @opjulian we would like to understand the current grant distribution process

**Comment by opjulian** [comment]
Hi @Immanuel-john -- please direct any questions to https://discord.gg/rnHm5PP5 (mission-grants channel)
