### ISSUE TITLE
🧪 Mad Science Project Idea: Onchain Movie

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#21]
**What is an Mad Science Project Idea?**

A Mad Science Project Idea is an idea for a project within the Optimism ecosystem that may not have clear value but is generally cool as heck. Mad Science Project Ideas make great hackathon projects and tend to be a great way to explore Optimism, OP Mainnet, and the OP Stack.

---

## Summary

[The OP Stack](https://stack.optimism.io/) makes it possible to easily spin up new rollups. You could make an entire rollup that just exists to host a single movie. It's not clear why you would do this, but that's the point of Mad Science Project Ideas. Have fun!

## Possible Features

- Create an OP Stack chain that hosts a movie.
- Allow people to add comments or reviews about the movie.
- Create a custom video player that downloads the movie.

**Comment by jacobleegithub** [comment]
Hello @smartcontracts 

Mad Science Project Idea - Onchain Movie is really interesting. I would like to share some of my research.

In 2019, I delved into the challenges associated with using blockchain Layer 1/2 for media storage, streaming, and download services. A major challenge identified was the necessity for distributed storage and robust computing power, particularly for tasks like user downloads and video transcoding.

To tackle these challenges, I investigated the potential of integrating IPFS Swarm technology. While Optimism, with its Layer 2 scaling solutions, excels in managing transactions within a blockchain framework, handling large files such as movies presents a different set of demands. The question I explored was whether Optimism could effectively support distributed file storage systems for managing large media files, especially in terms of providing sufficient bandwidth for user downloads. The goal was to determine if this integration could offer a more efficient alternative to centralized infrastructure.
![ipfs swam](https://github.com/ethereum-optimism/ecosystem-contributions/assets/14127551/05a4ee90-8c3e-4d44-858c-34476530fae1)

To illustrate these concepts, I created a short video demonstration in 2019, available here: https://youtu.be/RnYQCuQkVTA

This video demonstrates a prototype that integrates these technologies, showcasing their potential application in blockchain-based environments for paid movie streaming and downloading.

I am keen to hear your feedback and answer any questions you might have about this integration and its application in Onchain Movie services. Looking forward to discussion.

with best regards,
Jacob
