### ISSUE TITLE
Delegate Mission Request: Open-source transaction simulator 

### ISSUE THREAD

**Issue by opjulian** [ethereum-optimism/ecosystem-contributions#221]
# Delegate Mission Request: Open-source transaction simulator 

###  [Application Link](https://app.charmverse.io/op-grants/proposals/new?template=1a12736e-c025-4cb5-8cad-2ae53a46a950)

Make sure you’re logged in with Farcaster, and make sure you choose the correct S6 Mission field (this will be the same name as the title of this Mission Request). 

If you're having trouble joining the Optimism Grants Council space, join via this [invite link](https://app.charmverse.io/invite/5e28cc).

--- 

**Delegate Mission Request Summary:**

This mission is intended to provide a key, critical piece of tooling - simulating transactions before they go onchain. Tenderly provides a great service in this respect, but it would be great to see an open-source version of this that can be freely used and built on. This is a simple but essential component of the developer toolkit, and funding its building knocks out one of the higher-friction, higher-cost elements of developing for new and even veteran developers.

**S6 Intent**

[Intent 3: Grow application devs on the Superchain](https://gov.optimism.io/t/season-6-intents-ratification/8104)

**Proposing Delegate**

jackanorak

**Grant Amount**

50k OP allocated but expect competitive bids

**Should this Mission be fulfilled by one or multiple applicants:**

Multiple

**How will this Delegate Mission Request help accomplish the above Intent?**

The thesis here is to lower frictions to launching new projects among developers new to the onchain experience. Debugging isn’t a flashy component of the work—but it is an essential one. And it seems like a clearly valuable, fundamental thing to have for the EVM some ways for developers to simulate transactions without the overhead of using testnets or paid providers.

Easier time developing -> more developers. It’s that simple.

**What is required to execute this Mission Request?**

Open-source tool that allows developers to simulate the results of transactions without having to post them on mainnet. This core functionality may be delivered in any number of ways, so what is desired here is a potential scope of work to be provided by applicants.

**How should governance participants measure impact upon completion of this Mission?**

**Milestones:**

* Project scope and resource allocation, timelines set
* Completion of user interviews
* MVP
* Final build

**Metrics:**

* Github stars and forks
* Contributions

**Impact:**

- Superchain protocol testimonials
- Grantees and RPGF recipients indicating use of this tool

**Has anyone other than the proposer contributed to this Mission Request?**

No

## Which metric will the success of this Mission Request be evaluated against?

The North star metric against which this Mission Request should be evaluated is ***# of testnet transactions emitting event logs.*** This metric indicates the tool's active usage and reliability in a testing environment and reflects developer engagement. This metric was suggested by the Foundation and approved by the Grants Council.

**Comment by roninjin10** [comment]
Applied to implement a dev tool that can do this on top of tevm.sh 😎
