### ISSUE TITLE
🧪 Mad Science Project Idea: Generalized "Airline Miles" Rollup

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#26]
**What is an Mad Science Project Idea?**

A Mad Science Project Idea is an idea for a project within the Optimism ecosystem that may not have clear value but is generally cool as heck. Mad Science Project Ideas make great hackathon projects and tend to be a great way to explore Optimism, OP Mainnet, and the OP Stack.

---

## Summary

[The OP Stack](https://stack.optimism.io/) makes it possible to easily spin up new rollups. A common use-case pitched for crypto is bringing rewards points onchain. However, this tends to be too expensive on blockchains like Ethereum. To solve the cost problem, you could create a rollup entirely dedicated to rewards points. You could even create a framework for easily spinning up rewards programs hooked up to individual rollups.

## Possible Features

- Create an OP Stack chain that manages rewards points.
- Create a framework for launching OP Stack chains for rewards points.

**Comment by andyjsbell** [comment]
@smartcontracts I think this sounds interesting but would you be able to elaborate a little more please 🙏
