### ISSUE TITLE
🔴 Ecosystem Project Idea: OP Mainnet Gas Fee Tracker

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#3]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Tools like [ethgasstation](https://ethgasstation.info) help users understand the current transacting landscape on a blockchain. Currently, the best available tool for understanding the cost of using OP Mainnet is [l2fees.info](https://l2fees.info/) which only displays spot fees and does not show historical fees or the fees for using popular applications.

## Possible Features

- Display showing the current cost of transacting on OP Mainnet using common transaction types as reference points. Ideally these common transaction types include basic transfers, ERC20 transfers, swaps, and a series of transaction types pulled from popular apps on OP Mainnet.
- Display historical gas prices on OP Mainnet to show how gas prices have changed over time.
- Display the users and applications that are using the most gas on OP Mainnet over certain specified time ranges (1d, 7d, 30d, all time).

## Impact

- Users would have a better understanding of OP Mainnet fee behavior

**Comment by Lemma199** [comment]
👋 I see this is marked as **In Progress**. Is that still accurate? If not I might be interesting in hacking on this (not a frontend person historically, so should be a good learning opportunity too)

**Comment by smartcontracts** [comment]
Someone reached out to me and stated that they'd started hacking on this, lemme see if I can get them in here

**Comment by unnawut** [comment]
Hey all! It was me reaching out signaling my interest on this idea. My goal is to deliver not just something workable but should provide good value to OP ecosystem and not repeating existing contribution if any.

Sharing my study progress so far. 3 aspects I'm looking from:

## 1. Existing solutions

Sorted by number of available features:

| Tool | Live gas price | Live transaction cost by type | Historical transaction cost by type | Historical gas price | All time fees saved | L1 vs. L2 fee comparison | Gas guzzlers |
|--------|--------|--------|--------|--------|--------|--------|--------|
| [L2 Fees](https://l2fees.info/) | ❌ | ✅ (Send ETH, Swap Token) in USD | ❌ | ❌ | ❌ | ❌ | ❌ |
| [@optimismfnd / All-Time Stats & Gas Fee Savings](https://dune.com/optimismfnd/optimism-all-time-gas-fee-savings) | ❌ | ❌ | ❌ | ❌ | ✅ (USD, ETH) | ❌ | ❌ |
| [@optimismfnd / Fee Savings Calculator](https://dune.com/optimismfnd/How-Much-Could-You-Save-on-Optimism-Fee-Savings-Calculator) | ❌ | ❌ | ❌ | ❌ | ❌ | ✅ (USD, ETH) | ❌ |
| [Owlracle's Gas Price Tracker](https://owlracle.info/opt) | ✅ (gwei) | ❌ | ❌ | ✅ (gwei, 15 days) | ❌ | ❌ | ❌ |
| [Blockscout's Optimism Stats](https://optimism.blockscout.com/stats) | ✅ (gwei) | ❌ | ❌ | ✅ (gwei, 1 month) | ❌ |  ❌ | ❌ |
| [@oplabspbc / Optimism Gas Price Tracker](https://dune.com/oplabspbc/optimism-l2-gas-price-tracker) | ✅ | ❌ | ✅ (Swap, NFT ops, contract deploys) in ETH, USD, averaged | ✅ (gwei, 6 hours) | ❌ | ❌ | ❌ |
| [@oplabspbc / Optimism Bedrock Migration Impact](https://dune.com/oplabspbc/optimism-bedrock-migration-impact-dashboard) | ❌ | ❌ | ✅ (Swap, NFT ops, contract deploys) in ETH, USD, averaged | ✅ (gwei, 2 months) | ✅ (USD) | ✅ (USD, ETH, %) | ❌ |
| [Optimism's Grafana Gas Price Tracker](https://public-grafana.optimism.io/d/9hkhMxn7z/public-dashboard) | ✅ (gwei) | ✅ (Send ETH, Swap, NFT mint, contract deploys) in USD | ✅ (Send ETH, Swap, NFT mint, contract deploys) in USD, 1 month | ✅ (gwei, 6 hours) | ❌ |  ✅ (gwei) | ❌ |

So my general takeaways from these are:

- Existing tools _combined_ are pretty comprehensive, with Optimism's Grafana being the most feature complete
- The problem with the more detailed ones (Dune dashboards, Grafana) is that they are not too nice on the UX. The UX-friendlier ones (L2 Fees, Blockscout, Owlracle) on the other hand often focus on very narrow band of information and useful only for very specific purposes
- So tackling to build another tracker should be about building a tool that: 
  1. Does at least equal to or more than combination of existing solutions above
  2. Provides insights to both current and historical data
  3. Most importantly: is UX-pleasing and easily digestible, not just information provider

Which comes to my 2nd point below.

## 2. User experience

UX wise, I find these three sites as aspirations to the gas fee tracker:

<details>

<summary>MEV-Boost Dashboard: https://mevboost.pics/</summary>

![image](https://github.com/ethereum-optimism/ecosystem-contributions/assets/921194/b42536d9-d9cf-44e9-9bf1-9fb2ee4c9d38)

</details>
<details>

<summary>Ethereum Block Value Analytics: https://payload.de/data/</summary>

![image](https://github.com/ethereum-optimism/ecosystem-contributions/assets/921194/c3da1eaa-f46d-4a74-9f8c-b76b723f2f09)

</details>

<details>

<summary>Ultrasound.money: https://ultrasound.money/</summary>

![image](https://github.com/ethereum-optimism/ecosystem-contributions/assets/921194/c2195bd4-3762-4a70-911b-c7e4cc1344b7)

</details>

All in all, we could aspire the new tool to be 1) comparative like [MEV-Boost Dashboard](https://mevboost.pics/), 2) interactive like [Ethereum Block Value Analytics](https://payload.de/data/), and 3) easily-digestible, insightful and visually pleasing like [Ultrasound.money](https://ultrasound.money/)

## 3. Technical infrastructure

After hashing out the user requirements, some important items to keep in mind on the implementation side:

1. Design and infra for ETL of chain's raw data
2. Cost of serving long-running infrastructure, including: frontend/backend service, query node (cost depending on needing full node or archive node) -> perhaps require upfront grant once some significant development milestone achieved

## Next steps

I'll be looking more into pinning the necessart metrics, and some UX ideas on top of them. Would love to continue the conversation with anyone interested! <3

**Comment by unnawut** [comment]
Hey all just want to give a quick update that I will have to withdraw from this project idea due to other ongoing projects including an OP mission proposal that got accepted. Happy to support anyone who'd like to pick this up though!

**Comment by buildooor** [comment]
I started working on an Optimism gas tracker website.

The demo is hosted here:

https://optimism-gas-tracker.vercel.app/

It displays:

- Historical gas prices
- Common transaction types estimated costs
- Top gas guzzlers/spenders

The backend and frontend source code is available here (will open source soon):

https://github.com/buildooor/optimism-gas-tracker

It's built using React (Next.js), Node.js (express), leveldb (storage).
It queries CoinGecko for price and uses various public rpc urls to get block transactions for gas usage. 

There's more features to add and open to any initial feedback!

**Comment by buildooor** [comment]
cc @smartcontracts

**Comment by raynemang** [comment]
[0xOrphan](https://twitter.com/0xOrphan) built this via [decentragora](https://twitter.com/metaterminus): https://www.evmgasstation.xyz/

Just expanded to multiple chains. Price graph included and custom gas calculator.

**Comment by wslyvh** [comment]
I'll add another gas tracker that includes Optimism

https://www.useweb3.xyz/gas/optimism

**Comment by wslyvh** [comment]
Closed issue, but still seeing some traffic coming in from here.
So just a quick update as the tracker on useWeb3 will soon get deprecated.

It has been migrated to https://www.ethgastracker.com/network/optimism
Also available over API :)
