### ISSUE TITLE
🧪 Mad Science Project Idea: Bridge Lottery

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#31]
**What is an Mad Science Project Idea?**

A Mad Science Project Idea is an idea for a project within the Optimism ecosystem that may not have clear value but is generally cool as heck. Mad Science Project Ideas make great hackathon projects and tend to be a great way to explore Optimism, OP Mainnet, and the OP Stack.

---

## Summary

Create a "slot machine" application for the bridge that randomly rewards depositors into the OP Mainnet Standard Bridge with an NFT or some other token. Chances of being rewarded could be entirely random or could be proportional to assets deposited.

## Possible Features

- Randomly reward users for depositing into the OP Mainnet Standard Bridge.
- Allow users to see their rewards.

**Comment by xtycoonfi** [comment]
You asked for it, so we built it! ✅

**Check it out here** => [https://github.com/BridgeLottery](https://github.com/BridgeLottery) 🎈
