### ISSUE TITLE
🔴 Ecosystem Project Idea: Embedded Gateway Widget

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#35]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [Optimism Gateway app](https://app.optimism.io) is an easy way to transfer funds to and from OP Mainnet. Can you create an embedded version of the Gateway that other applications can easily include in their own websites? Ideally, this looks like a widget with a great design that mirrors the Optimism Gateway design.

## Possible Features

- Allow app developers to add the Embedded Gateway Widget to their own websites.
- Allow users to bridge funds to/from OP Mainnet via the Embedded Gateway Widget.

**Comment by vaibhavchellani** [comment]
Would you consider this as a solution? 
- has OP gateway
- a bunch of third party bridges as well for fast withdraws
- is completely open source and charges no fee
- is really good and being used in production by good teams

https://docs.socket.tech/socket-liquidity-layer/use-socketll/socket-plugin

**Comment by pumpgxd** [comment]
hi im going to start working on this

**Comment by Osas-dot** [comment]
> hi im going to start working on this

That'll be great
