### ISSUE TITLE
🔴 Ecosystem Project Idea: TokenList.org-Style Attestation List

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#36]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

[TokenList.org](https://tokenlist.org) is a website that allows users to publish and discover lists of tokens maintained by teams and projects. These lists of tokens make it possible for teams to signal the legitimacy of certain tokens and help users filter out spam. The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station/) needs a similar type of "Attestation List" specification and website that helps users understand which attestations/schemas are appropriate to use for which use-cases.

## Possible Features

- An instance of an attestation list following a standard JSON schema and can be hosted publicly on ENS, IPFS, or HTTPS.
- Context on what attestation lists are
- Directions on how to validate that a schemas follow the proposed standard
- Directions on how to author a attestation list
  - List data
    - List URL
    - List Name
    - List version
    - Link to the official homepage of the list manager
  - Attestation data
    - Attestation name
    - Attestation author
    - Attestation key
    - Attestation value
    - Attestation image
    - Attestation description
- Directions on how to deploy an attestation list
- Examples of what a attestation list looks like

**Comment by 0xyNaMu** [comment]
Gm gm, 
The link for the website has a typo and therefore doesn't work. Here is the right link: https://tokenlists.org/. The spelling should include an s: TokenLists.org
