### ISSUE TITLE
🔴 Ecosystem Project Idea: ATST Data Duplicator

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#37]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station/) is a central repository for attestations on OP Mainnet. One of the primary challenges currently facing the AttestationStation is the need to bootstrap the system with high-quality attestations. Luckily, blockchains already have an enormous amount of useful data that can be converted into attestations.

Some examples of existing blockchain data that can be converted into productive attestations are:
- Addresses that were part of the initial ETH genesis allocation
- Addresses that have held some NFT for more than X amount of time
- Addresses that have donated to GitCoin rounds
- Addresses that have received POAPs from important events

Converting this information into attestations makes it more accessible to developers and improves the quality of data in the AttestationStation generally. It would be valuable to have a project that can import this data into the AttestationStation in a verifiable way. Here, "verifiable" means that another user can replicate the process that was used to generate the attestations to confirm that all of the attestations were generated properly. That user can then trust that the attestations are correct and can begin to use them in their own applications.

## Possible Features

- Specify queries or scripts that pull blockchain data and convert that data into attestations
- Allow developers to easily reproduce the queries/scripts to verify the attestations
- Consider creating a system that makes it easy to do this for arbitrary queries.

**Comment by Linklinkguan** [comment]
Really good idea !
