### ISSUE TITLE
🔴 Ecosystem Project Idea: ATST Indexer

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#38]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station/) is a central repository for attestations on OP Mainnet. One of the primary challenges facing the AttestationStation today is that complex queries against the AttestationStation can be hard to execute. Developers are looking for easy, scalable ways to index the AttestationStation so that they can cheaply query the graph of attestations. The ideal AttestationStation indexer is efficient, easy to run, robust, and provides easy querying access to the full graph of attestations.

## Possible Features

- Allow developers to easily run the indexer.
- Allow developers to quickly query the ATST graph.

**Comment by Chomtana** [comment]
Hi, do we already have it in the new AttestationStation V1
https://github.com/ethereum-attestation-service/easter-indexer-v2

Also, I would like to expand it to support integration with our ENS-compatible resolver system specially designed to integrate with EAS. 

Submitted a grant proposal to grant council RFP-1: https://op-grants.charmverse.io/proposals?id=4e2eefd3-8902-4a9d-b6cc-3f343112a7fe

**Comment by Chomtana** [comment]
Also you should update your AttestationStation link to https://community.optimism.io/docs/identity/build/ as the old one result in 404 not found
