### ISSUE TITLE
📝 Draft Project Idea: Stop Snoozing!

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#43]
**What is a Draft Project Idea?**

A Draft Project Idea is a concept for a project within the Optimism ecosystem that is generally considered valuable but has not yet been fleshed out into a clearly defined product. Draft Project Ideas may be converted into Ecosystem Project Ideas as they are explored further and more thoroughly specified.

---

## Summary

Have a hard time waking up every day? Need something to keep you accountable? Introducing: Stop Snoozing!

Stop Snoozing! is a concept for a simple smart contract application that incentivizes you to wake up every day before a specified time. You can use [bokkypoobah's Solidity DateTime library](https://github.com/bokkypoobah/BokkyPooBahsDateTimeLibrary) to make sure that a transaction is triggered on a set schedule within a certain time range. Users can put some ETH or ERC20 tokens up as stake that will be taken away if the transaction isn't sent on time. Easy!

## Possible Features

- Allow users to easily set up a wakeup schedule
- Allow users to have a different wakeup schedule on different days of the week
- Allow users to put up some stake in ETH or ERC20 tokens
- Require users to trigger a transaction every day according to the wakeup schedule
- Take away the stake if the user fails to trigger the transaction

## Impact

- Stop Snoozing! is a fun application that gets users familiar with making transactions every day
- Waking up is hard, but it's easier when you have a strong incentive to do so!

## Resources

- [Solidity DateTime library](https://github.com/bokkypoobah/BokkyPooBahsDateTimeLibrary)

**Comment by dmars300** [comment]
I would definitely use this. Creative idea.

**Comment by robbiesumner** [comment]
Anybody already working on this? I'd love to participate!

**Comment by qingfengzxr** [comment]
Hello, what is the latest progress of this project? Can I proceed with the development?

**Comment by robbiesumner** [comment]
I don't think anyone is working on this, go ahead!

**Comment by jomynn** [comment]
Hi, Can I get more detail about this idea.

**Comment by Shanni** [comment]
Can we form a 9AM group
