### ISSUE TITLE
🔴 Ecosystem Project Idea: Events Ticketing Application

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#5]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station) is a simple and unified way to make attestations on OP Mainnet, OP Goerli, or any other OP Stack-based chain.

You can use the AttestationStation to create a ticketing application for events by allowing anyone to register an event, issue tickets, or revoke tickets. Everything should be represented as an attestation.

## Possible Features

- Allow organizers to register an event, and store event details onchain via attestations.
- Allow organizers to issue tickets via attestations.
- Allow organizers to revoke tickets via attestations.
- Allow organizers to verify tickets by scanning a QR code.

## Impact

- Ticketing data is very useful for other applications using the AttestationStation
- Crypto ticketing apps are lackluster right now and there is a strong need for better options
- More people would use the AttestationStation in general

**Comment by mgarciap** [comment]
> The [AttestationStation](https://community.optimism.io/docs/governance/attestation-station) is a simple and unified way to make attestations on OP Mainnet, OP Goerli, or any other OP Stack-based chain.

Broken Link (404). Shouldn't be https://community.optimism.io/docs/identity/atst-v1 ?

**Comment by TravisLeeRichardson** [comment]
This project looks interesting.

**Comment by smartcontracts** [comment]
@TravisLeeRichardson there's no proposal/application for projects that are not tagged as RFPs! You can start working on them on these projects at any time.

**Comment by wslyvh** [comment]
Sup 😎👋

I've been working on a ticketing solution called Show Up Protocol
https://github.com/wslyvh/show-up

[Show Up](https://www.showup.events/) is an onchain RSVP and Event management protocol designed to reshape event participation. It introduces a novel staking mechanism that aligns the incentives between event organizers and attendees.

- Higher event participation for event hosts
- Reward active participation for attendees
- A decentralized, open and permissionless protocol

win/win for everyone 🤝

Show Up Protocol is a set of decentralized, open, and permissionless smart contracts built on the Ethereum protocol. These contracts manage commitments and the conditions for keeping them. It is exclusively deployed on [Optimism](https://optimistic.etherscan.io/address/0x27d81f79D12327370cdB18DdEa03080621AEAadC) and [Base](https://basescan.org/address/0x27d81f79D12327370cdB18DdEa03080621AEAadC). The event metadata is stored on IPFS, ensuring the platform has no control over your events, funds, or payments.


*It doesn't use EAS attestations (yet) - altho we have been in touch
