### ISSUE TITLE
🔴 Ecosystem Project Idea: Generated Contract Docs

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#53]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

The [OP Stack](https://stack.optimism.io) contains various smart contracts that are currently held within the [contracts-bedrock](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock) package in the Optimism Monorepo. We'd like to make information about these smart contracts more accessible with an UI so that anyone looking to review the project can easily understand what's going on. This would be a static site that collects together automatically generated artifacts from the contracts-bedrock package and displays it in a digestible format.

In addition to the possible features noted below, feel free to mention any further artifacts that would improve the quality of the generated docs. These can be added to the monorepo.

## Possible Features

- List of contract names, addresses, and block explorer links to each contract
- Call graphs generated by [Slither](https://github.com/crytic/slither) or [Solidity Visual Auditor](https://consensys.net/diligence/blog/2019/10/solidity-visual-auditor-extension-for-vs-code/) to understand the relationships between contracts
- Dependency/inheritance graphs
- Slither detector output
- Code coverage detection
- Invariant docs
- Nicely rendered contract specs

## Impact

Better contract documentation makes contracts easier to review and helps auditors/whitehats more easily understand the system, which ultimately makes the OP Stack safer for its users.

**Comment by 0xJepsen** [comment]
Couldn't forge doc be used here? Something like [this](https://github.com/laudiacay/barustenberg/pull/5) it doesn't have all the features but maybe added them to forge doc would be better then rebuilding from scratch?
