### ISSUE TITLE
✨ Contribution Opportunity: Ensure generated CI mocks are up to date

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#54]
**What is a Contribution Opportunity?**

A Contribution Opportunity is a concrete task that you can work on to contribute to the Optimism Collective.

---

## Summary

The [Optimism Monorepo](https://github.com/ethereum-optimism/optimism) is one of the primary places where work happens on the [OP Stack](https://stack.optimism.io), the open source software stack that powers the Optimism Collective. The Monorepo relies on certain generated "mock" files for testing. It is important to make sure that the generated mocks stay up to date at all times.

Addressing this Contribution Opportunity requires the following:
- Add a target to the top-level [Makefile](https://github.com/ethereum-optimism/optimism/blob/develop/Makefile) that enters the `op-node` and `op-service` folders and executes the command `go generate ./...` in both
- Add a [ci job](https://github.com/ethereum-optimism/optimism/blob/a2b038ec4a7daa293d595a1890a1c2088a0bb651/.circleci/config.yml#L61) that executes this command and checks that no diff exists by running the command `git diff --exit code`, see [here](https://github.com/ethereum-optimism/optimism/blob/a2b038ec4a7daa293d595a1890a1c2088a0bb651/.circleci/config.yml#L1084) for an example

## Impact

Ensuring mocks are up to date means that testing CI jobs won't fail and that we're always testing the latest content.

**Comment by Lemma199** [comment]
I can take this on, feel free to assign it to me! Thanks for the effort in compiling and tagging these contribution opportunities 🙂

**Comment by smartcontracts** [comment]
@Lemma199 amazing! Please let me know if you have any questions about what to do and I'll get them answered.

**Comment by Lemma199** [comment]
I've opened a PR (https://github.com/ethereum-optimism/optimism/pull/5839) just waiting on someone to suggest how they'd like me to make `mockery` available in the CI environment.

**Comment by smartcontracts** [comment]
@Lemma199 great work here! Gonna close out this issue since it's been completed. Going to go through all of these later and issue attestations for people who have completed these tasks :-)
