### ISSUE TITLE
🔴 Ecosystem Project Idea: subDAO Primitive

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#57]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

[nintynick on Twitter](https://twitter.com/nintynick_/status/1659586048844877827), cofounder of [Hats Protocol](https://twitter.com/hatsprotocol), highlighted a missing primitive in the DAO space called the "subDAO". The subDAO structure was, in the tweet, defined as a structure for groups of 7-20 people with a level of baseline infrastructure that makes decision making easy without creating too much overhead.

## Potential Features

- Ideal for groups of 7-20 people
- Minimal voting weight infrastructure
- Ability to easily add/remove members
- All onchain
- NFT or attestation-based membership
- Ability to give some admin authorities to the DAO
- Voting-weight handled in a non-transferable way (no delegation)
- Ability to make voting weights immutable

## Impact

- Small groups of individuals need to be able to coordinate
- Current tools (multisigs) focus on very small groups with rigid requirements
- Other tools focus on larger groups
- Intermediate size is an underserved market

**Comment by Freo42069** [comment]
Is there a bounty associated with this?
