### ISSUE TITLE
🔴 Ecosystem Project Idea: List of Crypto Legal Public Goods

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#65]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Various members of the Ethereum and broader crypto ecosystems have worked on public goods within the legal space over the years. A list of these resources would be highly valuable for anyone looking to better understand the current crypto legal landscape. These can range from opinions by legal experts to explicit legal frameworks and DAO tooling.

## Possible Features

- List out public goods in the crypto legal space
- Give a brief explainer of what the public good is
- Link to the work and any relevant authors

## Impact

- Crypto legal space is confusing and this may help people get a better understanding
- Help highlight projects for potential inclusion in future RPGF rounds

**Comment by teresacd11** [comment]
Hello! Would love to jump on this!

**Comment by smartcontracts** [comment]
@teresacd11 go for it! Would love to see what you come up with

**Comment by twopats** [comment]
@teresacd11 hey! any updates? This is personally outside my field of comfort zone but crypto x legal is quite thought provoking

**Comment by teresacd11** [comment]
> @teresacd11 hey! any updates? This is personally outside my field of comfort zone but crypto x legal is quite thought-provoking

Hello! Haven't been able to work on this, but sent the info to the BanklessDAO Legal Guild to see if they want to have this as a project! Also, open to anyone if anyone wants to take the lead, I would gladly help!

**Comment by nicefacer** [comment]
I am available to jump on this right away. Can it be assigned to me?

**Comment by wheresaddie** [comment]
Im interested if you can tag/assign me .. thanks! @twopats @teresacd11 @smartcontracts

**Comment by philliprossii7** [comment]
Interested if you have room??
