### ISSUE TITLE
🔴 Ecosystem Project Idea: Audit Preparation Guide

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#66]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Audits are an important part of shipping smart contract software to production. Much of the value of an audit can be derived from the work that goes into preparing for the audit. A well-prepared audit can often lead to much better results than a hasty one.

A canonical audit preparation guide would be highly valuable to both Optimism and the broader Ethereum ecosystem. An ideal contributor for this task has significant experience with the auditing process and would be able to provide clear guidelines that anyone can follow to achieve the best audit results.

## Possible Features

- Explain when a project should be considering an audit
- Explain the type of testing that a project should have
- Explain the type of documentation that a project should have in general
- Explain the type of documentation that a project should be giving to an auditor
- Explain the audit process in general so that a developer can prepare for the nitty gritty details
- Describe situations that a developer should look out for during the audit process
- Explain failure modes in the audit process and how to avoid them
- Explain how to find the best auditor for a given audit
- Give an overview of the currently available auditing groups and the types of expertise they provide

## Impact

- Audits are expensive and a poorly prepared audit can be a huge waste of time and money
- Helps developers create safer and better-documented applications

**Comment by gigamesh** [comment]
I was thinking about tackling this but noticed OpenZeppelin has a pretty thorough audit guide [here](https://learn.openzeppelin.com/security-audits/readiness-guide). It's specifically about smart contracts but seems pretty applicable to any audit.
