### ISSUE TITLE
🔴 Ecosystem Project Idea: Liquidity Types Explainer

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#68]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Liquidity is an important factor for many applications. However, Liquidity comes in many different shapes and sizes. It would be highly valuable to have a detailed reference document that explains all the different ways that liquidity might be useful for a project. 

Examples of possible usecases for liquidity include:
- Liquidity for bridges that speeds up the process of moving assets between chains
- Liquidity for lending markets that makes an asset more widely available
- Liquidity for decentralized exchanges that reduces slippage when exchanging assets

## Possible Features

- Create a detailed list of the different ways liquidity might impact an application
- Give examples of different applications that make use of liquidity in the listed ways
- Describe potential ways that liquidity might be useful in the future

## Impact

- Liquidity can be confusing for those who aren't already familiar with it, this document would help reduce that gap
- Help illuminate what type of liquidity might influence the creation of what type of app

**Comment by JeremiahKamama** [comment]
I'd like to work on this
