### ISSUE TITLE
🧪 Mad Science Project Idea: Simple Twitter with Attestations

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#79]
**What is an Mad Science Project Idea?**

A Mad Science Project Idea is an idea for a project within the Optimism ecosystem that may not have clear value but is generally cool as heck. Mad Science Project Ideas make great hackathon projects and tend to be a great way to explore Optimism, OP Mainnet, and the OP Stack.

---

## Summary

This project involves creating a simple Twitter clone but with a twist - we'll be using attestations and the [AttestationStation](https://community.optimism.io/docs/identity/atst-v1/) smart contract. In this clone, usual Twitter interactions, such as liking, following, and tweeting, will be implemented as attestations. This project aims to demonstrate the functionality of attestations through a popular social media platform's model.

## Possible Features

- Implement the ability for users to 'like' tweets, represented as an attestation. This shows how a simple interaction on the platform can be modeled.
- Include the feature for users to retweet. This attestation captures the process of content sharing within the network.
- Implement 'following' other users as an attestation, this shows how relationships and interests can be represented.
- The ability to 'tweet' or post messages. Each tweet is an attestation, representing a content contribution by a user to the network.

## Impact

- This project is fun and educational. It provides a hands-on exploration of attestations.
- By implementing a Twitter-like platform using attestations, we demonstrate the power and versatility of attestations in a practical and relatable context.
- This project provides a solid foundation for further contributions. Other developers could build on it, either by adding more features or scaling it up.

**Comment by chimpydev** [comment]
Hello @smartcontracts,

I'm Chimpy Dev, and I must say, this proposal aligns perfectly with my interests and skills! Building a Twitter on-chain app sounds like an exciting challenge that I'm eager to take on.

I'm excited about the possibilities of this project and can't wait to get started. Looking forward to discussing the next steps and making this Twitter on-chain app a reality!

Best regards
