### ISSUE TITLE
🔴 Ecosystem Project Idea: Simple Robust Self-Hosted RPC Proxy

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#83]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

RPCs and their respective providers can sometimes pose considerable challenges for developers due to their varied limits. In certain cases, developers might find the free tiers insufficient for their needs, leading to the necessity of purchasing premium packages. A potential solution to this issue can be the development of a high-quality RPC proxy that developers can host themselves. The key objective is to make the proxy straightforward and easy-to-configure so that it is accessible to developers at different levels of experience.

## Possible Features

- It should be easy to set up, configure, and integrate with existing systems.
- The proxy should be capable of intelligently managing and routing requests to different providers based on their rate limits and the current request load.
- It should be resilient and fault-tolerant, with the ability to failover to different providers in the event of an outage or if rate limits are exceeded.
- The proxy should provide comprehensive logging and monitoring features to help developers understand the request load, rate limit usage, and the performance of different providers.
- It should be able to work around the tier limits so that users are spending as little money as possible by taking advantage of existing free tiers.
- Maybe some sort of UI for managing the proxy.

## Impact

- It could potentially save developers considerable time, effort, and money by removing the need to manage interactions with different RPC providers and their respective limits.
- By providing a robust and fault-tolerant solution, it can increase the reliability of applications that rely on RPCs.
- The enhanced logging and monitoring can provide valuable insights into the performance and usage of different RPC providers, which can inform optimization efforts and reduce costs.

**Comment by sambacha** [comment]
this is basically [dshackle](https://github.com/emeraldpay/dshackle)
