### ISSUE TITLE
🔴 Ecosystem Project Idea: Alternative Fault Detector

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#90]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

L2 state proposals are published to the L2OutputOracle contract, and it's crucial that these proposals align with the accurate L2 state. OP Labs has built a service—the fault detector—that confirms this. However, to enhance the robustness of the system, it would be useful to have a secondary, independent implementation of the fault detector. This will provide an extra layer of assurance and help detect any potential bugs in the current fault detector.

## Possible Features

- Listen for new output proposal events for a given L2 block number.
- Locally generate an output proposal for that specific L2 block number.
- Perform a comparison between the locally generated proposal and the one received.
- Flag any discrepancies between the two, raising an error when necessary.

## Impact

- Serve as a safeguard against potential bugs in the current fault detector.
- Enhance the reliability and security of our L2 state verification process.
- Provide peace of mind through this added layer of validation.

**Comment by aodhgan** [comment]
@smartcontracts just some questions about this: 
- interpreting this as an alternative implementation of `op-program`, does it need all the fault proof functionality or just yes/no that the derivation logic and state transition function matches the L2OracleOutput?
- what is the acceptance criteria (are there any restrictions around implmentation language/component reuse)?

**Comment by shuse2** [comment]
@aodhgan, if you are not working on this yet, we would like to take this forward 💪

**Comment by shuse2** [comment]
@smartcontracts 
Here's the link to alternative implementation of fault detector https://github.com/LiskHQ/op-fault-detector we built in Go.
Please take a look
