### ISSUE TITLE
🔴 Ecosystem Project Idea: Smart Contract Code Verifier

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#92]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

OP Mainnet and other OP Stack based chains encompass a multitude of smart contracts. It's crucial to have a tool or script that efficiently maps the code deployed on these blockchains to the code found within the corresponding GitHub repositories. This tool should be able to take a smart contract address (or list of addresses) and a commit hash and verify that the deployed code corresponds to the code from the specific commit hash.

## Possible Features

- Implement a tool or UI that accepts user inputs for L1 network name, contract address, and commit hash.
- Allow the tool to download the corresponding GitHub repository at the specified commit hash and initialize it.
- Compile contracts and compare the bytecode of the deployed contract with the actual bytecode.
- Design the tool to handle proxies if necessary.
- Throw alerts if unable to match the deployed code to what's in GitHub.

## Impact

- Enhances the safety of smart contract deployments by validating the origin of deployed code.
- Improves auditability by providing an explicit link between the codebase in the repository and the deployed smart contracts.

**Comment by sambacha** [comment]
Blockscout actually has their contract code verifier as a standalone service you can run,  

https://github.com/blockscout/blockscout-rs/blob/main/smart-contract-verifier/README.md

**Comment by kevin-fruitful** [comment]
I've been working on something like this - a Github action that can reconcile repository bytecode with on chain bytecode. The action will generate a report on each commit and if the bytecode doesn't match for a contract, then it'll state the previous commit which it does match such that it's easy to see where the deviations start to happen. I'll report back when I'm finished.

**Comment by roninjin10** [comment]
@sambacha integrating this into OP stack repos would be a good approach
