### ISSUE TITLE
🔴 Ecosystem Project Idea: Real Time OP Mainnet Bridge Dashboard

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#97]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

In the rapidly evolving landscape of Layer 2 solutions, an overarching understanding of cross-chain interactions and bridge activities is crucial. A real-time L2 Bridge Dashboard for OP Mainnet could provide a holistic view of all transaction activities across bridges connected to the OP Mainnet. This wouldn't just offer insights into the network's health, traffic, and usage trends, but also enhance the transparency and trust users have in the network. Users could better understand where liquidity is flowing, identify the most active bridges, and make informed decisions based on real-time data. For developers, such a dashboard could offer invaluable insights into user behavior and bridge performance, potentially guiding future development efforts and optimizations.

## Features 

- **Real-Time Data**: A dashboard that displays constantly updated, real-time data on transaction activities across all bridges connected to OP Mainnet.
- **Interactive UI**: A highly interactive user interface showcasing live flows of transactions.
- **Source Identification**: Feature to identify the source of funds and the corresponding bridge utilized.
- **Aggregated Statistics**: Display of aggregated statistics covering total volume, the number of transactions, average transaction size, bridge popularity, and more.

## Impact 

- **Better Understanding**: A comprehensive tool that aids users, developers, and researchers in understanding bridge usage dynamics in real-time.
- **Increased Transparency**: By providing a transparent view of transaction flows, the dashboard could significantly enhance users' trust in bridge operations.
- **Actionable Insights**: The aggregated statistics and real-time data can deliver actionable insights for users and developers, potentially influencing strategic decision-making and future development direction.

**Comment by mattick27** [comment]
I will take this !!!

**Comment by LvisWang** [comment]
Hey SixdegreeLab would love to work on this! 

- Website: https://sixdegree.xyz/
  - Dune: https://dune.com/sixdegree
  - Founded in summer 2022, Sixdegree is a team composed of data scientists and crypto researchers with experience working with 20+ protocols such as Lens, ParaSwap, Velodrome, Yearn among others as well as publishing 60+ Dune dashboards and being ranked top 4 team on Dune leaderboard
  - Sixdegree services have expanded from one-off Dune dashboard to full data-driven growth services including Dune dashboard, community talks, financial reporting, airdrop strategy and DeFi liquidity proposal among others
  - Some past examples of our work include: https://sixdegree.substack.com/p/user-engagement-analysis

**Comment by mattick27** [comment]
Already live at https://txbridge.xyz/. 
I continually update the information, gitbook, and docs incrementally

**Comment by vaibhavchellani** [comment]
Hey folks! We have built this already and its live for last 6months: socketscan.io

**Comment by 0xludobianco** [comment]
Hi! :) Is this stil open?
