### ISSUE TITLE
🔴 Ecosystem Project Idea: Public OP Mainnet Network Health Dashboard

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/ecosystem-contributions#99]
**What is an Ecosystem Project Idea?**

An Ecosystem Project Idea is an idea for a project that someone could build within the Optimism ecosystem. As opposed to an Ecosystem Concept or an Ecosystem Idea, an Ecosystem Project is generally more fleshed out and corresponds to a relatively clear product to be built. 

---

## Summary

Users need clear, constant insight into the functional behavior of OP Mainnet. In order to provide insights and better understanding of the state and performance of the L2 network, the L2 Network Health Dashboard will offer a range of crucial statistics in a visual, easy-to-understand format. As an important part of the ecosystem, the ability to monitor the health and performance of the L2 network will allow developers, users, and operators to make informed decisions and adjustments. 

## Features

- The dashboard should be built using Grafana for real-time monitoring and interaction.
- The dashboard should be fully open source.
- The dashboard should have instructions on how to populate the dashboard.
- The dashboard should track transaction latency and offer insights into the average, peak, and minimum transaction times.
- The dashboard should keep track of the costs associated with specific actions on the network.
- The dashboard should track the speed of block production and highlight any significant deviations.
- The dashboard should be able to track reorganizations on the network.
- The dashboard should be able to track the time taken for a block to be produced and sent to L1.
- The dashboard should track block finalization times.
- Flexibility for adding additional metrics or data points as they become relevant or necessary.

## Impact

- The dashboard will provide critical insights into the performance of the L2 network, allowing for informed decision making.
- The data collected and displayed could help identify any bottlenecks or areas of inefficiency on the network.
- By making this information easily accessible, the dashboard could encourage the growth and development of the network by providing developers with the information they need to optimize their applications and services.
- Having this kind of transparency could increase trust and confidence in the network. Users and developers alike will have a clearer understanding of how the network operates and performs under various conditions.

**Comment by nanobro** [comment]
I'm tackling this one!

**Comment by dmars300** [comment]
This is def something we need.

**Comment by 0x-dx** [comment]
@smartcontracts If it's still open, I can look into this.

**Comment by marianoclaveria** [comment]
@nanobro Can you please share the demo link? Would love to take a look. Thanks!

**Comment by Nicca42** [comment]
Heyo!

@nanobro if you are still interest in working on this it is getting moved into a markdown file. You can make a PR to add yourself as a contributor!

This process should wrap up by the end of the week, so look out for instructions in the README then.

As always, stay optimistic!

**Comment by nanobro** [comment]
@marianoclaveria @Nicca42 It's a shame to say this. But it's too complex for me, I failed. So sorry.
